// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hqyBinaryInSetting.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "hqyBinaryInSetting.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace hqyBinaryInPackage {
class BinaryInInfoDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<BinaryInInfo> {
} _BinaryInInfo_default_instance_;
class BinaryinSettingDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<BinaryinSetting> {
} _BinaryinSetting_default_instance_;

namespace protobuf_hqyBinaryInSetting_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BinaryInInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BinaryInInfo, ntype_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BinaryInInfo, fthreshold_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BinaryinSetting, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(BinaryinSetting, obinaryinfolist_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(BinaryInInfo)},
  { 6, -1, sizeof(BinaryinSetting)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_BinaryInInfo_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_BinaryinSetting_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "hqyBinaryInSetting.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace

void TableStruct::Shutdown() {
  _BinaryInInfo_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _BinaryinSetting_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _BinaryInInfo_default_instance_.DefaultConstruct();
  _BinaryinSetting_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\030hqyBinaryInSetting.proto\022\022hqyBinaryInP"
      "ackage\"S\n\014BinaryInInfo\022/\n\005ntype\030\001 \001(\0162 ."
      "hqyBinaryInPackage.BinaryInType\022\022\n\nfThre"
      "shold\030\002 \001(\002\"L\n\017BinaryinSetting\0229\n\017oBinar"
      "yInfoList\030\001 \003(\0132 .hqyBinaryInPackage.Bin"
      "aryInInfo*3\n\014BinaryInType\022\021\n\rBT_SampleMo"
      "de\020\000\022\020\n\014BT_EmptyMode\020\001*X\n\nBinaryInFD\022\016\n\n"
      "BFD_B_600V\020\000\022\016\n\nBFD_B_100V\020\001\022\r\n\tBFD_B_10"
      "V\020\002\022\014\n\010BFD_B_1V\020\003\022\r\n\tBFD_B_01V\020\004b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 360);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "hqyBinaryInSetting.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_hqyBinaryInSetting_2eproto

const ::google::protobuf::EnumDescriptor* BinaryInType_descriptor() {
  protobuf_hqyBinaryInSetting_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_hqyBinaryInSetting_2eproto::file_level_enum_descriptors[0];
}
bool BinaryInType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* BinaryInFD_descriptor() {
  protobuf_hqyBinaryInSetting_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_hqyBinaryInSetting_2eproto::file_level_enum_descriptors[1];
}
bool BinaryInFD_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BinaryInInfo::kNtypeFieldNumber;
const int BinaryInInfo::kFThresholdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BinaryInInfo::BinaryInInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_hqyBinaryInSetting_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:hqyBinaryInPackage.BinaryInInfo)
}
BinaryInInfo::BinaryInInfo(const BinaryInInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&ntype_, &from.ntype_,
    reinterpret_cast<char*>(&fthreshold_) -
    reinterpret_cast<char*>(&ntype_) + sizeof(fthreshold_));
  // @@protoc_insertion_point(copy_constructor:hqyBinaryInPackage.BinaryInInfo)
}

void BinaryInInfo::SharedCtor() {
  ::memset(&ntype_, 0, reinterpret_cast<char*>(&fthreshold_) -
    reinterpret_cast<char*>(&ntype_) + sizeof(fthreshold_));
  _cached_size_ = 0;
}

BinaryInInfo::~BinaryInInfo() {
  // @@protoc_insertion_point(destructor:hqyBinaryInPackage.BinaryInInfo)
  SharedDtor();
}

void BinaryInInfo::SharedDtor() {
}

void BinaryInInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* BinaryInInfo::descriptor() {
  protobuf_hqyBinaryInSetting_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_hqyBinaryInSetting_2eproto::file_level_metadata[0].descriptor;
}

const BinaryInInfo& BinaryInInfo::default_instance() {
  protobuf_hqyBinaryInSetting_2eproto::InitDefaults();
  return *internal_default_instance();
}

BinaryInInfo* BinaryInInfo::New(::google::protobuf::Arena* arena) const {
  BinaryInInfo* n = new BinaryInInfo;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void BinaryInInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:hqyBinaryInPackage.BinaryInInfo)
  ::memset(&ntype_, 0, reinterpret_cast<char*>(&fthreshold_) -
    reinterpret_cast<char*>(&ntype_) + sizeof(fthreshold_));
}

bool BinaryInInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:hqyBinaryInPackage.BinaryInInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .hqyBinaryInPackage.BinaryInType ntype = 1;
      case 1: {
        if (tag == 8u) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_ntype(static_cast< ::hqyBinaryInPackage::BinaryInType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float fThreshold = 2;
      case 2: {
        if (tag == 21u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &fthreshold_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:hqyBinaryInPackage.BinaryInInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:hqyBinaryInPackage.BinaryInInfo)
  return false;
#undef DO_
}

void BinaryInInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:hqyBinaryInPackage.BinaryInInfo)
  // .hqyBinaryInPackage.BinaryInType ntype = 1;
  if (this->ntype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->ntype(), output);
  }

  // float fThreshold = 2;
  if (this->fthreshold() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->fthreshold(), output);
  }

  // @@protoc_insertion_point(serialize_end:hqyBinaryInPackage.BinaryInInfo)
}

::google::protobuf::uint8* BinaryInInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:hqyBinaryInPackage.BinaryInInfo)
  // .hqyBinaryInPackage.BinaryInType ntype = 1;
  if (this->ntype() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->ntype(), target);
  }

  // float fThreshold = 2;
  if (this->fthreshold() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->fthreshold(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:hqyBinaryInPackage.BinaryInInfo)
  return target;
}

size_t BinaryInInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hqyBinaryInPackage.BinaryInInfo)
  size_t total_size = 0;

  // .hqyBinaryInPackage.BinaryInType ntype = 1;
  if (this->ntype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->ntype());
  }

  // float fThreshold = 2;
  if (this->fthreshold() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BinaryInInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:hqyBinaryInPackage.BinaryInInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const BinaryInInfo* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const BinaryInInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:hqyBinaryInPackage.BinaryInInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:hqyBinaryInPackage.BinaryInInfo)
    MergeFrom(*source);
  }
}

void BinaryInInfo::MergeFrom(const BinaryInInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:hqyBinaryInPackage.BinaryInInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.ntype() != 0) {
    set_ntype(from.ntype());
  }
  if (from.fthreshold() != 0) {
    set_fthreshold(from.fthreshold());
  }
}

void BinaryInInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:hqyBinaryInPackage.BinaryInInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BinaryInInfo::CopyFrom(const BinaryInInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hqyBinaryInPackage.BinaryInInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BinaryInInfo::IsInitialized() const {
  return true;
}

void BinaryInInfo::Swap(BinaryInInfo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BinaryInInfo::InternalSwap(BinaryInInfo* other) {
  std::swap(ntype_, other->ntype_);
  std::swap(fthreshold_, other->fthreshold_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata BinaryInInfo::GetMetadata() const {
  protobuf_hqyBinaryInSetting_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_hqyBinaryInSetting_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// BinaryInInfo

// .hqyBinaryInPackage.BinaryInType ntype = 1;
void BinaryInInfo::clear_ntype() {
  ntype_ = 0;
}
::hqyBinaryInPackage::BinaryInType BinaryInInfo::ntype() const {
  // @@protoc_insertion_point(field_get:hqyBinaryInPackage.BinaryInInfo.ntype)
  return static_cast< ::hqyBinaryInPackage::BinaryInType >(ntype_);
}
void BinaryInInfo::set_ntype(::hqyBinaryInPackage::BinaryInType value) {
  
  ntype_ = value;
  // @@protoc_insertion_point(field_set:hqyBinaryInPackage.BinaryInInfo.ntype)
}

// float fThreshold = 2;
void BinaryInInfo::clear_fthreshold() {
  fthreshold_ = 0;
}
float BinaryInInfo::fthreshold() const {
  // @@protoc_insertion_point(field_get:hqyBinaryInPackage.BinaryInInfo.fThreshold)
  return fthreshold_;
}
void BinaryInInfo::set_fthreshold(float value) {
  
  fthreshold_ = value;
  // @@protoc_insertion_point(field_set:hqyBinaryInPackage.BinaryInInfo.fThreshold)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BinaryinSetting::kOBinaryInfoListFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BinaryinSetting::BinaryinSetting()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_hqyBinaryInSetting_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:hqyBinaryInPackage.BinaryinSetting)
}
BinaryinSetting::BinaryinSetting(const BinaryinSetting& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      obinaryinfolist_(from.obinaryinfolist_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:hqyBinaryInPackage.BinaryinSetting)
}

void BinaryinSetting::SharedCtor() {
  _cached_size_ = 0;
}

BinaryinSetting::~BinaryinSetting() {
  // @@protoc_insertion_point(destructor:hqyBinaryInPackage.BinaryinSetting)
  SharedDtor();
}

void BinaryinSetting::SharedDtor() {
}

void BinaryinSetting::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* BinaryinSetting::descriptor() {
  protobuf_hqyBinaryInSetting_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_hqyBinaryInSetting_2eproto::file_level_metadata[1].descriptor;
}

const BinaryinSetting& BinaryinSetting::default_instance() {
  protobuf_hqyBinaryInSetting_2eproto::InitDefaults();
  return *internal_default_instance();
}

BinaryinSetting* BinaryinSetting::New(::google::protobuf::Arena* arena) const {
  BinaryinSetting* n = new BinaryinSetting;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void BinaryinSetting::Clear() {
// @@protoc_insertion_point(message_clear_start:hqyBinaryInPackage.BinaryinSetting)
  obinaryinfolist_.Clear();
}

bool BinaryinSetting::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:hqyBinaryInPackage.BinaryinSetting)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .hqyBinaryInPackage.BinaryInInfo oBinaryInfoList = 1;
      case 1: {
        if (tag == 10u) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_obinaryinfolist()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:hqyBinaryInPackage.BinaryinSetting)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:hqyBinaryInPackage.BinaryinSetting)
  return false;
#undef DO_
}

void BinaryinSetting::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:hqyBinaryInPackage.BinaryinSetting)
  // repeated .hqyBinaryInPackage.BinaryInInfo oBinaryInfoList = 1;
  for (unsigned int i = 0, n = this->obinaryinfolist_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->obinaryinfolist(i), output);
  }

  // @@protoc_insertion_point(serialize_end:hqyBinaryInPackage.BinaryinSetting)
}

::google::protobuf::uint8* BinaryinSetting::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:hqyBinaryInPackage.BinaryinSetting)
  // repeated .hqyBinaryInPackage.BinaryInInfo oBinaryInfoList = 1;
  for (unsigned int i = 0, n = this->obinaryinfolist_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->obinaryinfolist(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:hqyBinaryInPackage.BinaryinSetting)
  return target;
}

size_t BinaryinSetting::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hqyBinaryInPackage.BinaryinSetting)
  size_t total_size = 0;

  // repeated .hqyBinaryInPackage.BinaryInInfo oBinaryInfoList = 1;
  {
    unsigned int count = this->obinaryinfolist_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->obinaryinfolist(i));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void BinaryinSetting::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:hqyBinaryInPackage.BinaryinSetting)
  GOOGLE_DCHECK_NE(&from, this);
  const BinaryinSetting* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const BinaryinSetting>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:hqyBinaryInPackage.BinaryinSetting)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:hqyBinaryInPackage.BinaryinSetting)
    MergeFrom(*source);
  }
}

void BinaryinSetting::MergeFrom(const BinaryinSetting& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:hqyBinaryInPackage.BinaryinSetting)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  obinaryinfolist_.MergeFrom(from.obinaryinfolist_);
}

void BinaryinSetting::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:hqyBinaryInPackage.BinaryinSetting)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BinaryinSetting::CopyFrom(const BinaryinSetting& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hqyBinaryInPackage.BinaryinSetting)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BinaryinSetting::IsInitialized() const {
  return true;
}

void BinaryinSetting::Swap(BinaryinSetting* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BinaryinSetting::InternalSwap(BinaryinSetting* other) {
  obinaryinfolist_.UnsafeArenaSwap(&other->obinaryinfolist_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata BinaryinSetting::GetMetadata() const {
  protobuf_hqyBinaryInSetting_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_hqyBinaryInSetting_2eproto::file_level_metadata[1];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// BinaryinSetting

// repeated .hqyBinaryInPackage.BinaryInInfo oBinaryInfoList = 1;
int BinaryinSetting::obinaryinfolist_size() const {
  return obinaryinfolist_.size();
}
void BinaryinSetting::clear_obinaryinfolist() {
  obinaryinfolist_.Clear();
}
const ::hqyBinaryInPackage::BinaryInInfo& BinaryinSetting::obinaryinfolist(int index) const {
  // @@protoc_insertion_point(field_get:hqyBinaryInPackage.BinaryinSetting.oBinaryInfoList)
  return obinaryinfolist_.Get(index);
}
::hqyBinaryInPackage::BinaryInInfo* BinaryinSetting::mutable_obinaryinfolist(int index) {
  // @@protoc_insertion_point(field_mutable:hqyBinaryInPackage.BinaryinSetting.oBinaryInfoList)
  return obinaryinfolist_.Mutable(index);
}
::hqyBinaryInPackage::BinaryInInfo* BinaryinSetting::add_obinaryinfolist() {
  // @@protoc_insertion_point(field_add:hqyBinaryInPackage.BinaryinSetting.oBinaryInfoList)
  return obinaryinfolist_.Add();
}
::google::protobuf::RepeatedPtrField< ::hqyBinaryInPackage::BinaryInInfo >*
BinaryinSetting::mutable_obinaryinfolist() {
  // @@protoc_insertion_point(field_mutable_list:hqyBinaryInPackage.BinaryinSetting.oBinaryInfoList)
  return &obinaryinfolist_;
}
const ::google::protobuf::RepeatedPtrField< ::hqyBinaryInPackage::BinaryInInfo >&
BinaryinSetting::obinaryinfolist() const {
  // @@protoc_insertion_point(field_list:hqyBinaryInPackage.BinaryinSetting.oBinaryInfoList)
  return obinaryinfolist_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace hqyBinaryInPackage

// @@protoc_insertion_point(global_scope)
