// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hqyGooseSubscribe.proto

#ifndef PROTOBUF_hqyGooseSubscribe_2eproto__INCLUDED
#define PROTOBUF_hqyGooseSubscribe_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "hqyGooseCommon.pb.h"
// @@protoc_insertion_point(includes)
namespace hqyGooseCommon {
class Channel_Info;
class Channel_InfoDefaultTypeInternal;
extern Channel_InfoDefaultTypeInternal _Channel_Info_default_instance_;
class DataAtom;
class DataAtomDefaultTypeInternal;
extern DataAtomDefaultTypeInternal _DataAtom_default_instance_;
class UtcTime;
class UtcTimeDefaultTypeInternal;
extern UtcTimeDefaultTypeInternal _UtcTime_default_instance_;
}  // namespace hqyGooseCommon
namespace hqyGoose_Sub_Setting {
class Control_Block;
class Control_BlockDefaultTypeInternal;
extern Control_BlockDefaultTypeInternal _Control_Block_default_instance_;
class Goose_Sub;
class Goose_SubDefaultTypeInternal;
extern Goose_SubDefaultTypeInternal _Goose_Sub_default_instance_;
}  // namespace hqyGoose_Sub_Setting

namespace hqyGoose_Sub_Setting {

namespace protobuf_hqyGooseSubscribe_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_hqyGooseSubscribe_2eproto

// ===================================================================

class Control_Block : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hqyGoose_Sub_Setting.Control_Block) */ {
 public:
  Control_Block();
  virtual ~Control_Block();

  Control_Block(const Control_Block& from);

  inline Control_Block& operator=(const Control_Block& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Control_Block& default_instance();

  static inline const Control_Block* internal_default_instance() {
    return reinterpret_cast<const Control_Block*>(
               &_Control_Block_default_instance_);
  }

  void Swap(Control_Block* other);

  // implements Message ----------------------------------------------

  inline Control_Block* New() const PROTOBUF_FINAL { return New(NULL); }

  Control_Block* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Control_Block& from);
  void MergeFrom(const Control_Block& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Control_Block* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .hqyGooseCommon.Channel_Info Channel = 14;
  int channel_size() const;
  void clear_channel();
  static const int kChannelFieldNumber = 14;
  const ::hqyGooseCommon::Channel_Info& channel(int index) const;
  ::hqyGooseCommon::Channel_Info* mutable_channel(int index);
  ::hqyGooseCommon::Channel_Info* add_channel();
  ::google::protobuf::RepeatedPtrField< ::hqyGooseCommon::Channel_Info >*
      mutable_channel();
  const ::google::protobuf::RepeatedPtrField< ::hqyGooseCommon::Channel_Info >&
      channel() const;

  // string IedName = 1;
  void clear_iedname();
  static const int kIedNameFieldNumber = 1;
  const ::std::string& iedname() const;
  void set_iedname(const ::std::string& value);
  #if LANG_CXX11
  void set_iedname(::std::string&& value);
  #endif
  void set_iedname(const char* value);
  void set_iedname(const char* value, size_t size);
  ::std::string* mutable_iedname();
  ::std::string* release_iedname();
  void set_allocated_iedname(::std::string* iedname);

  // string gocbRef = 2;
  void clear_gocbref();
  static const int kGocbRefFieldNumber = 2;
  const ::std::string& gocbref() const;
  void set_gocbref(const ::std::string& value);
  #if LANG_CXX11
  void set_gocbref(::std::string&& value);
  #endif
  void set_gocbref(const char* value);
  void set_gocbref(const char* value, size_t size);
  ::std::string* mutable_gocbref();
  ::std::string* release_gocbref();
  void set_allocated_gocbref(::std::string* gocbref);

  // string goID = 3;
  void clear_goid();
  static const int kGoIDFieldNumber = 3;
  const ::std::string& goid() const;
  void set_goid(const ::std::string& value);
  #if LANG_CXX11
  void set_goid(::std::string&& value);
  #endif
  void set_goid(const char* value);
  void set_goid(const char* value, size_t size);
  ::std::string* mutable_goid();
  ::std::string* release_goid();
  void set_allocated_goid(::std::string* goid);

  // string DestMac = 5;
  void clear_destmac();
  static const int kDestMacFieldNumber = 5;
  const ::std::string& destmac() const;
  void set_destmac(const ::std::string& value);
  #if LANG_CXX11
  void set_destmac(::std::string&& value);
  #endif
  void set_destmac(const char* value);
  void set_destmac(const char* value, size_t size);
  ::std::string* mutable_destmac();
  ::std::string* release_destmac();
  void set_allocated_destmac(::std::string* destmac);

  // string DataSet = 8;
  void clear_dataset();
  static const int kDataSetFieldNumber = 8;
  const ::std::string& dataset() const;
  void set_dataset(const ::std::string& value);
  #if LANG_CXX11
  void set_dataset(::std::string&& value);
  #endif
  void set_dataset(const char* value);
  void set_dataset(const char* value, size_t size);
  ::std::string* mutable_dataset();
  ::std::string* release_dataset();
  void set_allocated_dataset(::std::string* dataset);

  // uint32 APPID = 4;
  void clear_appid();
  static const int kAPPIDFieldNumber = 4;
  ::google::protobuf::uint32 appid() const;
  void set_appid(::google::protobuf::uint32 value);

  // uint32 ConfRecv = 6;
  void clear_confrecv();
  static const int kConfRecvFieldNumber = 6;
  ::google::protobuf::uint32 confrecv() const;
  void set_confrecv(::google::protobuf::uint32 value);

  // uint32 timeAllowToLive = 7;
  void clear_timeallowtolive();
  static const int kTimeAllowToLiveFieldNumber = 7;
  ::google::protobuf::uint32 timeallowtolive() const;
  void set_timeallowtolive(::google::protobuf::uint32 value);

  // int32 Port = 11;
  void clear_port();
  static const int kPortFieldNumber = 11;
  ::google::protobuf::int32 port() const;
  void set_port(::google::protobuf::int32 value);

  // bool ndsCom = 9;
  void clear_ndscom();
  static const int kNdsComFieldNumber = 9;
  bool ndscom() const;
  void set_ndscom(bool value);

  // bool testFlag = 10;
  void clear_testflag();
  static const int kTestFlagFieldNumber = 10;
  bool testflag() const;
  void set_testflag(bool value);

  // bool IsSubscribe = 12;
  void clear_issubscribe();
  static const int kIsSubscribeFieldNumber = 12;
  bool issubscribe() const;
  void set_issubscribe(bool value);

  // bool NoGoCB = 13;
  void clear_nogocb();
  static const int kNoGoCBFieldNumber = 13;
  bool nogocb() const;
  void set_nogocb(bool value);

  // @@protoc_insertion_point(class_scope:hqyGoose_Sub_Setting.Control_Block)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::hqyGooseCommon::Channel_Info > channel_;
  ::google::protobuf::internal::ArenaStringPtr iedname_;
  ::google::protobuf::internal::ArenaStringPtr gocbref_;
  ::google::protobuf::internal::ArenaStringPtr goid_;
  ::google::protobuf::internal::ArenaStringPtr destmac_;
  ::google::protobuf::internal::ArenaStringPtr dataset_;
  ::google::protobuf::uint32 appid_;
  ::google::protobuf::uint32 confrecv_;
  ::google::protobuf::uint32 timeallowtolive_;
  ::google::protobuf::int32 port_;
  bool ndscom_;
  bool testflag_;
  bool issubscribe_;
  bool nogocb_;
  mutable int _cached_size_;
  friend struct  protobuf_hqyGooseSubscribe_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Goose_Sub : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hqyGoose_Sub_Setting.Goose_Sub) */ {
 public:
  Goose_Sub();
  virtual ~Goose_Sub();

  Goose_Sub(const Goose_Sub& from);

  inline Goose_Sub& operator=(const Goose_Sub& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Goose_Sub& default_instance();

  static inline const Goose_Sub* internal_default_instance() {
    return reinterpret_cast<const Goose_Sub*>(
               &_Goose_Sub_default_instance_);
  }

  void Swap(Goose_Sub* other);

  // implements Message ----------------------------------------------

  inline Goose_Sub* New() const PROTOBUF_FINAL { return New(NULL); }

  Goose_Sub* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Goose_Sub& from);
  void MergeFrom(const Goose_Sub& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Goose_Sub* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .hqyGoose_Sub_Setting.Control_Block Block = 1;
  int block_size() const;
  void clear_block();
  static const int kBlockFieldNumber = 1;
  const ::hqyGoose_Sub_Setting::Control_Block& block(int index) const;
  ::hqyGoose_Sub_Setting::Control_Block* mutable_block(int index);
  ::hqyGoose_Sub_Setting::Control_Block* add_block();
  ::google::protobuf::RepeatedPtrField< ::hqyGoose_Sub_Setting::Control_Block >*
      mutable_block();
  const ::google::protobuf::RepeatedPtrField< ::hqyGoose_Sub_Setting::Control_Block >&
      block() const;

  // @@protoc_insertion_point(class_scope:hqyGoose_Sub_Setting.Goose_Sub)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::hqyGoose_Sub_Setting::Control_Block > block_;
  mutable int _cached_size_;
  friend struct  protobuf_hqyGooseSubscribe_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Control_Block

// string IedName = 1;
inline void Control_Block::clear_iedname() {
  iedname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Control_Block::iedname() const {
  // @@protoc_insertion_point(field_get:hqyGoose_Sub_Setting.Control_Block.IedName)
  return iedname_.GetNoArena();
}
inline void Control_Block::set_iedname(const ::std::string& value) {
  
  iedname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hqyGoose_Sub_Setting.Control_Block.IedName)
}
#if LANG_CXX11
inline void Control_Block::set_iedname(::std::string&& value) {
  
  iedname_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hqyGoose_Sub_Setting.Control_Block.IedName)
}
#endif
inline void Control_Block::set_iedname(const char* value) {
  
  iedname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hqyGoose_Sub_Setting.Control_Block.IedName)
}
inline void Control_Block::set_iedname(const char* value, size_t size) {
  
  iedname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hqyGoose_Sub_Setting.Control_Block.IedName)
}
inline ::std::string* Control_Block::mutable_iedname() {
  
  // @@protoc_insertion_point(field_mutable:hqyGoose_Sub_Setting.Control_Block.IedName)
  return iedname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Control_Block::release_iedname() {
  // @@protoc_insertion_point(field_release:hqyGoose_Sub_Setting.Control_Block.IedName)
  
  return iedname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Control_Block::set_allocated_iedname(::std::string* iedname) {
  if (iedname != NULL) {
    
  } else {
    
  }
  iedname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), iedname);
  // @@protoc_insertion_point(field_set_allocated:hqyGoose_Sub_Setting.Control_Block.IedName)
}

// string gocbRef = 2;
inline void Control_Block::clear_gocbref() {
  gocbref_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Control_Block::gocbref() const {
  // @@protoc_insertion_point(field_get:hqyGoose_Sub_Setting.Control_Block.gocbRef)
  return gocbref_.GetNoArena();
}
inline void Control_Block::set_gocbref(const ::std::string& value) {
  
  gocbref_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hqyGoose_Sub_Setting.Control_Block.gocbRef)
}
#if LANG_CXX11
inline void Control_Block::set_gocbref(::std::string&& value) {
  
  gocbref_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hqyGoose_Sub_Setting.Control_Block.gocbRef)
}
#endif
inline void Control_Block::set_gocbref(const char* value) {
  
  gocbref_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hqyGoose_Sub_Setting.Control_Block.gocbRef)
}
inline void Control_Block::set_gocbref(const char* value, size_t size) {
  
  gocbref_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hqyGoose_Sub_Setting.Control_Block.gocbRef)
}
inline ::std::string* Control_Block::mutable_gocbref() {
  
  // @@protoc_insertion_point(field_mutable:hqyGoose_Sub_Setting.Control_Block.gocbRef)
  return gocbref_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Control_Block::release_gocbref() {
  // @@protoc_insertion_point(field_release:hqyGoose_Sub_Setting.Control_Block.gocbRef)
  
  return gocbref_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Control_Block::set_allocated_gocbref(::std::string* gocbref) {
  if (gocbref != NULL) {
    
  } else {
    
  }
  gocbref_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), gocbref);
  // @@protoc_insertion_point(field_set_allocated:hqyGoose_Sub_Setting.Control_Block.gocbRef)
}

// string goID = 3;
inline void Control_Block::clear_goid() {
  goid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Control_Block::goid() const {
  // @@protoc_insertion_point(field_get:hqyGoose_Sub_Setting.Control_Block.goID)
  return goid_.GetNoArena();
}
inline void Control_Block::set_goid(const ::std::string& value) {
  
  goid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hqyGoose_Sub_Setting.Control_Block.goID)
}
#if LANG_CXX11
inline void Control_Block::set_goid(::std::string&& value) {
  
  goid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hqyGoose_Sub_Setting.Control_Block.goID)
}
#endif
inline void Control_Block::set_goid(const char* value) {
  
  goid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hqyGoose_Sub_Setting.Control_Block.goID)
}
inline void Control_Block::set_goid(const char* value, size_t size) {
  
  goid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hqyGoose_Sub_Setting.Control_Block.goID)
}
inline ::std::string* Control_Block::mutable_goid() {
  
  // @@protoc_insertion_point(field_mutable:hqyGoose_Sub_Setting.Control_Block.goID)
  return goid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Control_Block::release_goid() {
  // @@protoc_insertion_point(field_release:hqyGoose_Sub_Setting.Control_Block.goID)
  
  return goid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Control_Block::set_allocated_goid(::std::string* goid) {
  if (goid != NULL) {
    
  } else {
    
  }
  goid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), goid);
  // @@protoc_insertion_point(field_set_allocated:hqyGoose_Sub_Setting.Control_Block.goID)
}

// uint32 APPID = 4;
inline void Control_Block::clear_appid() {
  appid_ = 0u;
}
inline ::google::protobuf::uint32 Control_Block::appid() const {
  // @@protoc_insertion_point(field_get:hqyGoose_Sub_Setting.Control_Block.APPID)
  return appid_;
}
inline void Control_Block::set_appid(::google::protobuf::uint32 value) {
  
  appid_ = value;
  // @@protoc_insertion_point(field_set:hqyGoose_Sub_Setting.Control_Block.APPID)
}

// string DestMac = 5;
inline void Control_Block::clear_destmac() {
  destmac_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Control_Block::destmac() const {
  // @@protoc_insertion_point(field_get:hqyGoose_Sub_Setting.Control_Block.DestMac)
  return destmac_.GetNoArena();
}
inline void Control_Block::set_destmac(const ::std::string& value) {
  
  destmac_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hqyGoose_Sub_Setting.Control_Block.DestMac)
}
#if LANG_CXX11
inline void Control_Block::set_destmac(::std::string&& value) {
  
  destmac_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hqyGoose_Sub_Setting.Control_Block.DestMac)
}
#endif
inline void Control_Block::set_destmac(const char* value) {
  
  destmac_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hqyGoose_Sub_Setting.Control_Block.DestMac)
}
inline void Control_Block::set_destmac(const char* value, size_t size) {
  
  destmac_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hqyGoose_Sub_Setting.Control_Block.DestMac)
}
inline ::std::string* Control_Block::mutable_destmac() {
  
  // @@protoc_insertion_point(field_mutable:hqyGoose_Sub_Setting.Control_Block.DestMac)
  return destmac_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Control_Block::release_destmac() {
  // @@protoc_insertion_point(field_release:hqyGoose_Sub_Setting.Control_Block.DestMac)
  
  return destmac_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Control_Block::set_allocated_destmac(::std::string* destmac) {
  if (destmac != NULL) {
    
  } else {
    
  }
  destmac_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), destmac);
  // @@protoc_insertion_point(field_set_allocated:hqyGoose_Sub_Setting.Control_Block.DestMac)
}

// uint32 ConfRecv = 6;
inline void Control_Block::clear_confrecv() {
  confrecv_ = 0u;
}
inline ::google::protobuf::uint32 Control_Block::confrecv() const {
  // @@protoc_insertion_point(field_get:hqyGoose_Sub_Setting.Control_Block.ConfRecv)
  return confrecv_;
}
inline void Control_Block::set_confrecv(::google::protobuf::uint32 value) {
  
  confrecv_ = value;
  // @@protoc_insertion_point(field_set:hqyGoose_Sub_Setting.Control_Block.ConfRecv)
}

// uint32 timeAllowToLive = 7;
inline void Control_Block::clear_timeallowtolive() {
  timeallowtolive_ = 0u;
}
inline ::google::protobuf::uint32 Control_Block::timeallowtolive() const {
  // @@protoc_insertion_point(field_get:hqyGoose_Sub_Setting.Control_Block.timeAllowToLive)
  return timeallowtolive_;
}
inline void Control_Block::set_timeallowtolive(::google::protobuf::uint32 value) {
  
  timeallowtolive_ = value;
  // @@protoc_insertion_point(field_set:hqyGoose_Sub_Setting.Control_Block.timeAllowToLive)
}

// string DataSet = 8;
inline void Control_Block::clear_dataset() {
  dataset_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Control_Block::dataset() const {
  // @@protoc_insertion_point(field_get:hqyGoose_Sub_Setting.Control_Block.DataSet)
  return dataset_.GetNoArena();
}
inline void Control_Block::set_dataset(const ::std::string& value) {
  
  dataset_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hqyGoose_Sub_Setting.Control_Block.DataSet)
}
#if LANG_CXX11
inline void Control_Block::set_dataset(::std::string&& value) {
  
  dataset_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hqyGoose_Sub_Setting.Control_Block.DataSet)
}
#endif
inline void Control_Block::set_dataset(const char* value) {
  
  dataset_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hqyGoose_Sub_Setting.Control_Block.DataSet)
}
inline void Control_Block::set_dataset(const char* value, size_t size) {
  
  dataset_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hqyGoose_Sub_Setting.Control_Block.DataSet)
}
inline ::std::string* Control_Block::mutable_dataset() {
  
  // @@protoc_insertion_point(field_mutable:hqyGoose_Sub_Setting.Control_Block.DataSet)
  return dataset_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Control_Block::release_dataset() {
  // @@protoc_insertion_point(field_release:hqyGoose_Sub_Setting.Control_Block.DataSet)
  
  return dataset_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Control_Block::set_allocated_dataset(::std::string* dataset) {
  if (dataset != NULL) {
    
  } else {
    
  }
  dataset_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), dataset);
  // @@protoc_insertion_point(field_set_allocated:hqyGoose_Sub_Setting.Control_Block.DataSet)
}

// bool ndsCom = 9;
inline void Control_Block::clear_ndscom() {
  ndscom_ = false;
}
inline bool Control_Block::ndscom() const {
  // @@protoc_insertion_point(field_get:hqyGoose_Sub_Setting.Control_Block.ndsCom)
  return ndscom_;
}
inline void Control_Block::set_ndscom(bool value) {
  
  ndscom_ = value;
  // @@protoc_insertion_point(field_set:hqyGoose_Sub_Setting.Control_Block.ndsCom)
}

// bool testFlag = 10;
inline void Control_Block::clear_testflag() {
  testflag_ = false;
}
inline bool Control_Block::testflag() const {
  // @@protoc_insertion_point(field_get:hqyGoose_Sub_Setting.Control_Block.testFlag)
  return testflag_;
}
inline void Control_Block::set_testflag(bool value) {
  
  testflag_ = value;
  // @@protoc_insertion_point(field_set:hqyGoose_Sub_Setting.Control_Block.testFlag)
}

// int32 Port = 11;
inline void Control_Block::clear_port() {
  port_ = 0;
}
inline ::google::protobuf::int32 Control_Block::port() const {
  // @@protoc_insertion_point(field_get:hqyGoose_Sub_Setting.Control_Block.Port)
  return port_;
}
inline void Control_Block::set_port(::google::protobuf::int32 value) {
  
  port_ = value;
  // @@protoc_insertion_point(field_set:hqyGoose_Sub_Setting.Control_Block.Port)
}

// bool IsSubscribe = 12;
inline void Control_Block::clear_issubscribe() {
  issubscribe_ = false;
}
inline bool Control_Block::issubscribe() const {
  // @@protoc_insertion_point(field_get:hqyGoose_Sub_Setting.Control_Block.IsSubscribe)
  return issubscribe_;
}
inline void Control_Block::set_issubscribe(bool value) {
  
  issubscribe_ = value;
  // @@protoc_insertion_point(field_set:hqyGoose_Sub_Setting.Control_Block.IsSubscribe)
}

// bool NoGoCB = 13;
inline void Control_Block::clear_nogocb() {
  nogocb_ = false;
}
inline bool Control_Block::nogocb() const {
  // @@protoc_insertion_point(field_get:hqyGoose_Sub_Setting.Control_Block.NoGoCB)
  return nogocb_;
}
inline void Control_Block::set_nogocb(bool value) {
  
  nogocb_ = value;
  // @@protoc_insertion_point(field_set:hqyGoose_Sub_Setting.Control_Block.NoGoCB)
}

// repeated .hqyGooseCommon.Channel_Info Channel = 14;
inline int Control_Block::channel_size() const {
  return channel_.size();
}
inline void Control_Block::clear_channel() {
  channel_.Clear();
}
inline const ::hqyGooseCommon::Channel_Info& Control_Block::channel(int index) const {
  // @@protoc_insertion_point(field_get:hqyGoose_Sub_Setting.Control_Block.Channel)
  return channel_.Get(index);
}
inline ::hqyGooseCommon::Channel_Info* Control_Block::mutable_channel(int index) {
  // @@protoc_insertion_point(field_mutable:hqyGoose_Sub_Setting.Control_Block.Channel)
  return channel_.Mutable(index);
}
inline ::hqyGooseCommon::Channel_Info* Control_Block::add_channel() {
  // @@protoc_insertion_point(field_add:hqyGoose_Sub_Setting.Control_Block.Channel)
  return channel_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::hqyGooseCommon::Channel_Info >*
Control_Block::mutable_channel() {
  // @@protoc_insertion_point(field_mutable_list:hqyGoose_Sub_Setting.Control_Block.Channel)
  return &channel_;
}
inline const ::google::protobuf::RepeatedPtrField< ::hqyGooseCommon::Channel_Info >&
Control_Block::channel() const {
  // @@protoc_insertion_point(field_list:hqyGoose_Sub_Setting.Control_Block.Channel)
  return channel_;
}

// -------------------------------------------------------------------

// Goose_Sub

// repeated .hqyGoose_Sub_Setting.Control_Block Block = 1;
inline int Goose_Sub::block_size() const {
  return block_.size();
}
inline void Goose_Sub::clear_block() {
  block_.Clear();
}
inline const ::hqyGoose_Sub_Setting::Control_Block& Goose_Sub::block(int index) const {
  // @@protoc_insertion_point(field_get:hqyGoose_Sub_Setting.Goose_Sub.Block)
  return block_.Get(index);
}
inline ::hqyGoose_Sub_Setting::Control_Block* Goose_Sub::mutable_block(int index) {
  // @@protoc_insertion_point(field_mutable:hqyGoose_Sub_Setting.Goose_Sub.Block)
  return block_.Mutable(index);
}
inline ::hqyGoose_Sub_Setting::Control_Block* Goose_Sub::add_block() {
  // @@protoc_insertion_point(field_add:hqyGoose_Sub_Setting.Goose_Sub.Block)
  return block_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::hqyGoose_Sub_Setting::Control_Block >*
Goose_Sub::mutable_block() {
  // @@protoc_insertion_point(field_mutable_list:hqyGoose_Sub_Setting.Goose_Sub.Block)
  return &block_;
}
inline const ::google::protobuf::RepeatedPtrField< ::hqyGoose_Sub_Setting::Control_Block >&
Goose_Sub::block() const {
  // @@protoc_insertion_point(field_list:hqyGoose_Sub_Setting.Goose_Sub.Block)
  return block_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace hqyGoose_Sub_Setting

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_hqyGooseSubscribe_2eproto__INCLUDED
