// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hqyiec6004478.proto

#ifndef PROTOBUF_hqyiec6004478_2eproto__INCLUDED
#define PROTOBUF_hqyiec6004478_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace hqyIEC60044_7_8_Setting {
class Channel_Info;
class Channel_InfoDefaultTypeInternal;
extern Channel_InfoDefaultTypeInternal _Channel_Info_default_instance_;
class Control_Block;
class Control_BlockDefaultTypeInternal;
extern Control_BlockDefaultTypeInternal _Control_Block_default_instance_;
class IEC60044_7_8;
class IEC60044_7_8DefaultTypeInternal;
extern IEC60044_7_8DefaultTypeInternal _IEC60044_7_8_default_instance_;
}  // namespace hqyIEC60044_7_8_Setting

namespace hqyIEC60044_7_8_Setting {

namespace protobuf_hqyiec6004478_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_hqyiec6004478_2eproto

enum Channel_Type {
  FOR_PROTECT = 0,
  FOR_MEASURE = 1,
  FOR_VOLTAGE = 2,
  Channel_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Channel_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Channel_Type_IsValid(int value);
const Channel_Type Channel_Type_MIN = FOR_PROTECT;
const Channel_Type Channel_Type_MAX = FOR_VOLTAGE;
const int Channel_Type_ARRAYSIZE = Channel_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* Channel_Type_descriptor();
inline const ::std::string& Channel_Type_Name(Channel_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    Channel_Type_descriptor(), value);
}
inline bool Channel_Type_Parse(
    const ::std::string& name, Channel_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Channel_Type>(
    Channel_Type_descriptor(), name, value);
}
// ===================================================================

class Channel_Info : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hqyIEC60044_7_8_Setting.Channel_Info) */ {
 public:
  Channel_Info();
  virtual ~Channel_Info();

  Channel_Info(const Channel_Info& from);

  inline Channel_Info& operator=(const Channel_Info& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Channel_Info& default_instance();

  static inline const Channel_Info* internal_default_instance() {
    return reinterpret_cast<const Channel_Info*>(
               &_Channel_Info_default_instance_);
  }

  void Swap(Channel_Info* other);

  // implements Message ----------------------------------------------

  inline Channel_Info* New() const PROTOBUF_FINAL { return New(NULL); }

  Channel_Info* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Channel_Info& from);
  void MergeFrom(const Channel_Info& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Channel_Info* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string Name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // string Description = 2;
  void clear_description();
  static const int kDescriptionFieldNumber = 2;
  const ::std::string& description() const;
  void set_description(const ::std::string& value);
  #if LANG_CXX11
  void set_description(::std::string&& value);
  #endif
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  ::std::string* mutable_description();
  ::std::string* release_description();
  void set_allocated_description(::std::string* description);

  // string MapId = 3;
  void clear_mapid();
  static const int kMapIdFieldNumber = 3;
  const ::std::string& mapid() const;
  void set_mapid(const ::std::string& value);
  #if LANG_CXX11
  void set_mapid(::std::string&& value);
  #endif
  void set_mapid(const char* value);
  void set_mapid(const char* value, size_t size);
  ::std::string* mutable_mapid();
  ::std::string* release_mapid();
  void set_allocated_mapid(::std::string* mapid);

  // .hqyIEC60044_7_8_Setting.Channel_Type Type = 4;
  void clear_type();
  static const int kTypeFieldNumber = 4;
  ::hqyIEC60044_7_8_Setting::Channel_Type type() const;
  void set_type(::hqyIEC60044_7_8_Setting::Channel_Type value);

  // @@protoc_insertion_point(class_scope:hqyIEC60044_7_8_Setting.Channel_Info)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr description_;
  ::google::protobuf::internal::ArenaStringPtr mapid_;
  int type_;
  mutable int _cached_size_;
  friend struct  protobuf_hqyiec6004478_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Control_Block : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hqyIEC60044_7_8_Setting.Control_Block) */ {
 public:
  Control_Block();
  virtual ~Control_Block();

  Control_Block(const Control_Block& from);

  inline Control_Block& operator=(const Control_Block& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Control_Block& default_instance();

  static inline const Control_Block* internal_default_instance() {
    return reinterpret_cast<const Control_Block*>(
               &_Control_Block_default_instance_);
  }

  void Swap(Control_Block* other);

  // implements Message ----------------------------------------------

  inline Control_Block* New() const PROTOBUF_FINAL { return New(NULL); }

  Control_Block* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Control_Block& from);
  void MergeFrom(const Control_Block& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Control_Block* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .hqyIEC60044_7_8_Setting.Channel_Info Channel = 8;
  int channel_size() const;
  void clear_channel();
  static const int kChannelFieldNumber = 8;
  const ::hqyIEC60044_7_8_Setting::Channel_Info& channel(int index) const;
  ::hqyIEC60044_7_8_Setting::Channel_Info* mutable_channel(int index);
  ::hqyIEC60044_7_8_Setting::Channel_Info* add_channel();
  ::google::protobuf::RepeatedPtrField< ::hqyIEC60044_7_8_Setting::Channel_Info >*
      mutable_channel();
  const ::google::protobuf::RepeatedPtrField< ::hqyIEC60044_7_8_Setting::Channel_Info >&
      channel() const;

  // string desc = 7;
  void clear_desc();
  static const int kDescFieldNumber = 7;
  const ::std::string& desc() const;
  void set_desc(const ::std::string& value);
  #if LANG_CXX11
  void set_desc(::std::string&& value);
  #endif
  void set_desc(const char* value);
  void set_desc(const char* value, size_t size);
  ::std::string* mutable_desc();
  ::std::string* release_desc();
  void set_allocated_desc(::std::string* desc);

  // uint32 LDName = 1;
  void clear_ldname();
  static const int kLDNameFieldNumber = 1;
  ::google::protobuf::uint32 ldname() const;
  void set_ldname(::google::protobuf::uint32 value);

  // uint32 DataSetName = 2;
  void clear_datasetname();
  static const int kDataSetNameFieldNumber = 2;
  ::google::protobuf::uint32 datasetname() const;
  void set_datasetname(::google::protobuf::uint32 value);

  // uint32 StateFlag1 = 3;
  void clear_stateflag1();
  static const int kStateFlag1FieldNumber = 3;
  ::google::protobuf::uint32 stateflag1() const;
  void set_stateflag1(::google::protobuf::uint32 value);

  // uint32 StateFlag2 = 4;
  void clear_stateflag2();
  static const int kStateFlag2FieldNumber = 4;
  ::google::protobuf::uint32 stateflag2() const;
  void set_stateflag2(::google::protobuf::uint32 value);

  // uint32 RatedDelayTime = 5;
  void clear_rateddelaytime();
  static const int kRatedDelayTimeFieldNumber = 5;
  ::google::protobuf::uint32 rateddelaytime() const;
  void set_rateddelaytime(::google::protobuf::uint32 value);

  // int32 Port = 6;
  void clear_port();
  static const int kPortFieldNumber = 6;
  ::google::protobuf::int32 port() const;
  void set_port(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:hqyIEC60044_7_8_Setting.Control_Block)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::hqyIEC60044_7_8_Setting::Channel_Info > channel_;
  ::google::protobuf::internal::ArenaStringPtr desc_;
  ::google::protobuf::uint32 ldname_;
  ::google::protobuf::uint32 datasetname_;
  ::google::protobuf::uint32 stateflag1_;
  ::google::protobuf::uint32 stateflag2_;
  ::google::protobuf::uint32 rateddelaytime_;
  ::google::protobuf::int32 port_;
  mutable int _cached_size_;
  friend struct  protobuf_hqyiec6004478_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class IEC60044_7_8 : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hqyIEC60044_7_8_Setting.IEC60044_7_8) */ {
 public:
  IEC60044_7_8();
  virtual ~IEC60044_7_8();

  IEC60044_7_8(const IEC60044_7_8& from);

  inline IEC60044_7_8& operator=(const IEC60044_7_8& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const IEC60044_7_8& default_instance();

  static inline const IEC60044_7_8* internal_default_instance() {
    return reinterpret_cast<const IEC60044_7_8*>(
               &_IEC60044_7_8_default_instance_);
  }

  void Swap(IEC60044_7_8* other);

  // implements Message ----------------------------------------------

  inline IEC60044_7_8* New() const PROTOBUF_FINAL { return New(NULL); }

  IEC60044_7_8* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const IEC60044_7_8& from);
  void MergeFrom(const IEC60044_7_8& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(IEC60044_7_8* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .hqyIEC60044_7_8_Setting.Control_Block Block = 1;
  int block_size() const;
  void clear_block();
  static const int kBlockFieldNumber = 1;
  const ::hqyIEC60044_7_8_Setting::Control_Block& block(int index) const;
  ::hqyIEC60044_7_8_Setting::Control_Block* mutable_block(int index);
  ::hqyIEC60044_7_8_Setting::Control_Block* add_block();
  ::google::protobuf::RepeatedPtrField< ::hqyIEC60044_7_8_Setting::Control_Block >*
      mutable_block();
  const ::google::protobuf::RepeatedPtrField< ::hqyIEC60044_7_8_Setting::Control_Block >&
      block() const;

  // int32 SamplingRatio = 2;
  void clear_samplingratio();
  static const int kSamplingRatioFieldNumber = 2;
  ::google::protobuf::int32 samplingratio() const;
  void set_samplingratio(::google::protobuf::int32 value);

  // int32 ASDUCount = 3;
  void clear_asducount();
  static const int kASDUCountFieldNumber = 3;
  ::google::protobuf::int32 asducount() const;
  void set_asducount(::google::protobuf::int32 value);

  // int32 SCP = 4;
  void clear_scp();
  static const int kSCPFieldNumber = 4;
  ::google::protobuf::int32 scp() const;
  void set_scp(::google::protobuf::int32 value);

  // int32 SCM = 5;
  void clear_scm();
  static const int kSCMFieldNumber = 5;
  ::google::protobuf::int32 scm() const;
  void set_scm(::google::protobuf::int32 value);

  // int32 SV = 6;
  void clear_sv();
  static const int kSVFieldNumber = 6;
  ::google::protobuf::int32 sv() const;
  void set_sv(::google::protobuf::int32 value);

  // int32 TargetDevSamplingRatio = 7;
  void clear_targetdevsamplingratio();
  static const int kTargetDevSamplingRatioFieldNumber = 7;
  ::google::protobuf::int32 targetdevsamplingratio() const;
  void set_targetdevsamplingratio(::google::protobuf::int32 value);

  // double RatedProtectCurrent = 9;
  void clear_ratedprotectcurrent();
  static const int kRatedProtectCurrentFieldNumber = 9;
  double ratedprotectcurrent() const;
  void set_ratedprotectcurrent(double value);

  // double RatedZeroSeqCurrent = 10;
  void clear_ratedzeroseqcurrent();
  static const int kRatedZeroSeqCurrentFieldNumber = 10;
  double ratedzeroseqcurrent() const;
  void set_ratedzeroseqcurrent(double value);

  // int32 BaudRate = 8;
  void clear_baudrate();
  static const int kBaudRateFieldNumber = 8;
  ::google::protobuf::int32 baudrate() const;
  void set_baudrate(::google::protobuf::int32 value);

  // bool OutputIsPrimary = 12;
  void clear_outputisprimary();
  static const int kOutputIsPrimaryFieldNumber = 12;
  bool outputisprimary() const;
  void set_outputisprimary(bool value);

  // double RatedPhaseVoltage = 11;
  void clear_ratedphasevoltage();
  static const int kRatedPhaseVoltageFieldNumber = 11;
  double ratedphasevoltage() const;
  void set_ratedphasevoltage(double value);

  // @@protoc_insertion_point(class_scope:hqyIEC60044_7_8_Setting.IEC60044_7_8)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::hqyIEC60044_7_8_Setting::Control_Block > block_;
  ::google::protobuf::int32 samplingratio_;
  ::google::protobuf::int32 asducount_;
  ::google::protobuf::int32 scp_;
  ::google::protobuf::int32 scm_;
  ::google::protobuf::int32 sv_;
  ::google::protobuf::int32 targetdevsamplingratio_;
  double ratedprotectcurrent_;
  double ratedzeroseqcurrent_;
  ::google::protobuf::int32 baudrate_;
  bool outputisprimary_;
  double ratedphasevoltage_;
  mutable int _cached_size_;
  friend struct  protobuf_hqyiec6004478_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Channel_Info

// string Name = 1;
inline void Channel_Info::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Channel_Info::name() const {
  // @@protoc_insertion_point(field_get:hqyIEC60044_7_8_Setting.Channel_Info.Name)
  return name_.GetNoArena();
}
inline void Channel_Info::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hqyIEC60044_7_8_Setting.Channel_Info.Name)
}
#if LANG_CXX11
inline void Channel_Info::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hqyIEC60044_7_8_Setting.Channel_Info.Name)
}
#endif
inline void Channel_Info::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hqyIEC60044_7_8_Setting.Channel_Info.Name)
}
inline void Channel_Info::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hqyIEC60044_7_8_Setting.Channel_Info.Name)
}
inline ::std::string* Channel_Info::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:hqyIEC60044_7_8_Setting.Channel_Info.Name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Channel_Info::release_name() {
  // @@protoc_insertion_point(field_release:hqyIEC60044_7_8_Setting.Channel_Info.Name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Channel_Info::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:hqyIEC60044_7_8_Setting.Channel_Info.Name)
}

// string Description = 2;
inline void Channel_Info::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Channel_Info::description() const {
  // @@protoc_insertion_point(field_get:hqyIEC60044_7_8_Setting.Channel_Info.Description)
  return description_.GetNoArena();
}
inline void Channel_Info::set_description(const ::std::string& value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hqyIEC60044_7_8_Setting.Channel_Info.Description)
}
#if LANG_CXX11
inline void Channel_Info::set_description(::std::string&& value) {
  
  description_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hqyIEC60044_7_8_Setting.Channel_Info.Description)
}
#endif
inline void Channel_Info::set_description(const char* value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hqyIEC60044_7_8_Setting.Channel_Info.Description)
}
inline void Channel_Info::set_description(const char* value, size_t size) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hqyIEC60044_7_8_Setting.Channel_Info.Description)
}
inline ::std::string* Channel_Info::mutable_description() {
  
  // @@protoc_insertion_point(field_mutable:hqyIEC60044_7_8_Setting.Channel_Info.Description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Channel_Info::release_description() {
  // @@protoc_insertion_point(field_release:hqyIEC60044_7_8_Setting.Channel_Info.Description)
  
  return description_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Channel_Info::set_allocated_description(::std::string* description) {
  if (description != NULL) {
    
  } else {
    
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:hqyIEC60044_7_8_Setting.Channel_Info.Description)
}

// string MapId = 3;
inline void Channel_Info::clear_mapid() {
  mapid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Channel_Info::mapid() const {
  // @@protoc_insertion_point(field_get:hqyIEC60044_7_8_Setting.Channel_Info.MapId)
  return mapid_.GetNoArena();
}
inline void Channel_Info::set_mapid(const ::std::string& value) {
  
  mapid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hqyIEC60044_7_8_Setting.Channel_Info.MapId)
}
#if LANG_CXX11
inline void Channel_Info::set_mapid(::std::string&& value) {
  
  mapid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hqyIEC60044_7_8_Setting.Channel_Info.MapId)
}
#endif
inline void Channel_Info::set_mapid(const char* value) {
  
  mapid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hqyIEC60044_7_8_Setting.Channel_Info.MapId)
}
inline void Channel_Info::set_mapid(const char* value, size_t size) {
  
  mapid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hqyIEC60044_7_8_Setting.Channel_Info.MapId)
}
inline ::std::string* Channel_Info::mutable_mapid() {
  
  // @@protoc_insertion_point(field_mutable:hqyIEC60044_7_8_Setting.Channel_Info.MapId)
  return mapid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Channel_Info::release_mapid() {
  // @@protoc_insertion_point(field_release:hqyIEC60044_7_8_Setting.Channel_Info.MapId)
  
  return mapid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Channel_Info::set_allocated_mapid(::std::string* mapid) {
  if (mapid != NULL) {
    
  } else {
    
  }
  mapid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), mapid);
  // @@protoc_insertion_point(field_set_allocated:hqyIEC60044_7_8_Setting.Channel_Info.MapId)
}

// .hqyIEC60044_7_8_Setting.Channel_Type Type = 4;
inline void Channel_Info::clear_type() {
  type_ = 0;
}
inline ::hqyIEC60044_7_8_Setting::Channel_Type Channel_Info::type() const {
  // @@protoc_insertion_point(field_get:hqyIEC60044_7_8_Setting.Channel_Info.Type)
  return static_cast< ::hqyIEC60044_7_8_Setting::Channel_Type >(type_);
}
inline void Channel_Info::set_type(::hqyIEC60044_7_8_Setting::Channel_Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:hqyIEC60044_7_8_Setting.Channel_Info.Type)
}

// -------------------------------------------------------------------

// Control_Block

// uint32 LDName = 1;
inline void Control_Block::clear_ldname() {
  ldname_ = 0u;
}
inline ::google::protobuf::uint32 Control_Block::ldname() const {
  // @@protoc_insertion_point(field_get:hqyIEC60044_7_8_Setting.Control_Block.LDName)
  return ldname_;
}
inline void Control_Block::set_ldname(::google::protobuf::uint32 value) {
  
  ldname_ = value;
  // @@protoc_insertion_point(field_set:hqyIEC60044_7_8_Setting.Control_Block.LDName)
}

// uint32 DataSetName = 2;
inline void Control_Block::clear_datasetname() {
  datasetname_ = 0u;
}
inline ::google::protobuf::uint32 Control_Block::datasetname() const {
  // @@protoc_insertion_point(field_get:hqyIEC60044_7_8_Setting.Control_Block.DataSetName)
  return datasetname_;
}
inline void Control_Block::set_datasetname(::google::protobuf::uint32 value) {
  
  datasetname_ = value;
  // @@protoc_insertion_point(field_set:hqyIEC60044_7_8_Setting.Control_Block.DataSetName)
}

// uint32 StateFlag1 = 3;
inline void Control_Block::clear_stateflag1() {
  stateflag1_ = 0u;
}
inline ::google::protobuf::uint32 Control_Block::stateflag1() const {
  // @@protoc_insertion_point(field_get:hqyIEC60044_7_8_Setting.Control_Block.StateFlag1)
  return stateflag1_;
}
inline void Control_Block::set_stateflag1(::google::protobuf::uint32 value) {
  
  stateflag1_ = value;
  // @@protoc_insertion_point(field_set:hqyIEC60044_7_8_Setting.Control_Block.StateFlag1)
}

// uint32 StateFlag2 = 4;
inline void Control_Block::clear_stateflag2() {
  stateflag2_ = 0u;
}
inline ::google::protobuf::uint32 Control_Block::stateflag2() const {
  // @@protoc_insertion_point(field_get:hqyIEC60044_7_8_Setting.Control_Block.StateFlag2)
  return stateflag2_;
}
inline void Control_Block::set_stateflag2(::google::protobuf::uint32 value) {
  
  stateflag2_ = value;
  // @@protoc_insertion_point(field_set:hqyIEC60044_7_8_Setting.Control_Block.StateFlag2)
}

// uint32 RatedDelayTime = 5;
inline void Control_Block::clear_rateddelaytime() {
  rateddelaytime_ = 0u;
}
inline ::google::protobuf::uint32 Control_Block::rateddelaytime() const {
  // @@protoc_insertion_point(field_get:hqyIEC60044_7_8_Setting.Control_Block.RatedDelayTime)
  return rateddelaytime_;
}
inline void Control_Block::set_rateddelaytime(::google::protobuf::uint32 value) {
  
  rateddelaytime_ = value;
  // @@protoc_insertion_point(field_set:hqyIEC60044_7_8_Setting.Control_Block.RatedDelayTime)
}

// int32 Port = 6;
inline void Control_Block::clear_port() {
  port_ = 0;
}
inline ::google::protobuf::int32 Control_Block::port() const {
  // @@protoc_insertion_point(field_get:hqyIEC60044_7_8_Setting.Control_Block.Port)
  return port_;
}
inline void Control_Block::set_port(::google::protobuf::int32 value) {
  
  port_ = value;
  // @@protoc_insertion_point(field_set:hqyIEC60044_7_8_Setting.Control_Block.Port)
}

// string desc = 7;
inline void Control_Block::clear_desc() {
  desc_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Control_Block::desc() const {
  // @@protoc_insertion_point(field_get:hqyIEC60044_7_8_Setting.Control_Block.desc)
  return desc_.GetNoArena();
}
inline void Control_Block::set_desc(const ::std::string& value) {
  
  desc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hqyIEC60044_7_8_Setting.Control_Block.desc)
}
#if LANG_CXX11
inline void Control_Block::set_desc(::std::string&& value) {
  
  desc_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hqyIEC60044_7_8_Setting.Control_Block.desc)
}
#endif
inline void Control_Block::set_desc(const char* value) {
  
  desc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hqyIEC60044_7_8_Setting.Control_Block.desc)
}
inline void Control_Block::set_desc(const char* value, size_t size) {
  
  desc_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hqyIEC60044_7_8_Setting.Control_Block.desc)
}
inline ::std::string* Control_Block::mutable_desc() {
  
  // @@protoc_insertion_point(field_mutable:hqyIEC60044_7_8_Setting.Control_Block.desc)
  return desc_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Control_Block::release_desc() {
  // @@protoc_insertion_point(field_release:hqyIEC60044_7_8_Setting.Control_Block.desc)
  
  return desc_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Control_Block::set_allocated_desc(::std::string* desc) {
  if (desc != NULL) {
    
  } else {
    
  }
  desc_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), desc);
  // @@protoc_insertion_point(field_set_allocated:hqyIEC60044_7_8_Setting.Control_Block.desc)
}

// repeated .hqyIEC60044_7_8_Setting.Channel_Info Channel = 8;
inline int Control_Block::channel_size() const {
  return channel_.size();
}
inline void Control_Block::clear_channel() {
  channel_.Clear();
}
inline const ::hqyIEC60044_7_8_Setting::Channel_Info& Control_Block::channel(int index) const {
  // @@protoc_insertion_point(field_get:hqyIEC60044_7_8_Setting.Control_Block.Channel)
  return channel_.Get(index);
}
inline ::hqyIEC60044_7_8_Setting::Channel_Info* Control_Block::mutable_channel(int index) {
  // @@protoc_insertion_point(field_mutable:hqyIEC60044_7_8_Setting.Control_Block.Channel)
  return channel_.Mutable(index);
}
inline ::hqyIEC60044_7_8_Setting::Channel_Info* Control_Block::add_channel() {
  // @@protoc_insertion_point(field_add:hqyIEC60044_7_8_Setting.Control_Block.Channel)
  return channel_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::hqyIEC60044_7_8_Setting::Channel_Info >*
Control_Block::mutable_channel() {
  // @@protoc_insertion_point(field_mutable_list:hqyIEC60044_7_8_Setting.Control_Block.Channel)
  return &channel_;
}
inline const ::google::protobuf::RepeatedPtrField< ::hqyIEC60044_7_8_Setting::Channel_Info >&
Control_Block::channel() const {
  // @@protoc_insertion_point(field_list:hqyIEC60044_7_8_Setting.Control_Block.Channel)
  return channel_;
}

// -------------------------------------------------------------------

// IEC60044_7_8

// repeated .hqyIEC60044_7_8_Setting.Control_Block Block = 1;
inline int IEC60044_7_8::block_size() const {
  return block_.size();
}
inline void IEC60044_7_8::clear_block() {
  block_.Clear();
}
inline const ::hqyIEC60044_7_8_Setting::Control_Block& IEC60044_7_8::block(int index) const {
  // @@protoc_insertion_point(field_get:hqyIEC60044_7_8_Setting.IEC60044_7_8.Block)
  return block_.Get(index);
}
inline ::hqyIEC60044_7_8_Setting::Control_Block* IEC60044_7_8::mutable_block(int index) {
  // @@protoc_insertion_point(field_mutable:hqyIEC60044_7_8_Setting.IEC60044_7_8.Block)
  return block_.Mutable(index);
}
inline ::hqyIEC60044_7_8_Setting::Control_Block* IEC60044_7_8::add_block() {
  // @@protoc_insertion_point(field_add:hqyIEC60044_7_8_Setting.IEC60044_7_8.Block)
  return block_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::hqyIEC60044_7_8_Setting::Control_Block >*
IEC60044_7_8::mutable_block() {
  // @@protoc_insertion_point(field_mutable_list:hqyIEC60044_7_8_Setting.IEC60044_7_8.Block)
  return &block_;
}
inline const ::google::protobuf::RepeatedPtrField< ::hqyIEC60044_7_8_Setting::Control_Block >&
IEC60044_7_8::block() const {
  // @@protoc_insertion_point(field_list:hqyIEC60044_7_8_Setting.IEC60044_7_8.Block)
  return block_;
}

// int32 SamplingRatio = 2;
inline void IEC60044_7_8::clear_samplingratio() {
  samplingratio_ = 0;
}
inline ::google::protobuf::int32 IEC60044_7_8::samplingratio() const {
  // @@protoc_insertion_point(field_get:hqyIEC60044_7_8_Setting.IEC60044_7_8.SamplingRatio)
  return samplingratio_;
}
inline void IEC60044_7_8::set_samplingratio(::google::protobuf::int32 value) {
  
  samplingratio_ = value;
  // @@protoc_insertion_point(field_set:hqyIEC60044_7_8_Setting.IEC60044_7_8.SamplingRatio)
}

// int32 ASDUCount = 3;
inline void IEC60044_7_8::clear_asducount() {
  asducount_ = 0;
}
inline ::google::protobuf::int32 IEC60044_7_8::asducount() const {
  // @@protoc_insertion_point(field_get:hqyIEC60044_7_8_Setting.IEC60044_7_8.ASDUCount)
  return asducount_;
}
inline void IEC60044_7_8::set_asducount(::google::protobuf::int32 value) {
  
  asducount_ = value;
  // @@protoc_insertion_point(field_set:hqyIEC60044_7_8_Setting.IEC60044_7_8.ASDUCount)
}

// int32 SCP = 4;
inline void IEC60044_7_8::clear_scp() {
  scp_ = 0;
}
inline ::google::protobuf::int32 IEC60044_7_8::scp() const {
  // @@protoc_insertion_point(field_get:hqyIEC60044_7_8_Setting.IEC60044_7_8.SCP)
  return scp_;
}
inline void IEC60044_7_8::set_scp(::google::protobuf::int32 value) {
  
  scp_ = value;
  // @@protoc_insertion_point(field_set:hqyIEC60044_7_8_Setting.IEC60044_7_8.SCP)
}

// int32 SCM = 5;
inline void IEC60044_7_8::clear_scm() {
  scm_ = 0;
}
inline ::google::protobuf::int32 IEC60044_7_8::scm() const {
  // @@protoc_insertion_point(field_get:hqyIEC60044_7_8_Setting.IEC60044_7_8.SCM)
  return scm_;
}
inline void IEC60044_7_8::set_scm(::google::protobuf::int32 value) {
  
  scm_ = value;
  // @@protoc_insertion_point(field_set:hqyIEC60044_7_8_Setting.IEC60044_7_8.SCM)
}

// int32 SV = 6;
inline void IEC60044_7_8::clear_sv() {
  sv_ = 0;
}
inline ::google::protobuf::int32 IEC60044_7_8::sv() const {
  // @@protoc_insertion_point(field_get:hqyIEC60044_7_8_Setting.IEC60044_7_8.SV)
  return sv_;
}
inline void IEC60044_7_8::set_sv(::google::protobuf::int32 value) {
  
  sv_ = value;
  // @@protoc_insertion_point(field_set:hqyIEC60044_7_8_Setting.IEC60044_7_8.SV)
}

// int32 TargetDevSamplingRatio = 7;
inline void IEC60044_7_8::clear_targetdevsamplingratio() {
  targetdevsamplingratio_ = 0;
}
inline ::google::protobuf::int32 IEC60044_7_8::targetdevsamplingratio() const {
  // @@protoc_insertion_point(field_get:hqyIEC60044_7_8_Setting.IEC60044_7_8.TargetDevSamplingRatio)
  return targetdevsamplingratio_;
}
inline void IEC60044_7_8::set_targetdevsamplingratio(::google::protobuf::int32 value) {
  
  targetdevsamplingratio_ = value;
  // @@protoc_insertion_point(field_set:hqyIEC60044_7_8_Setting.IEC60044_7_8.TargetDevSamplingRatio)
}

// int32 BaudRate = 8;
inline void IEC60044_7_8::clear_baudrate() {
  baudrate_ = 0;
}
inline ::google::protobuf::int32 IEC60044_7_8::baudrate() const {
  // @@protoc_insertion_point(field_get:hqyIEC60044_7_8_Setting.IEC60044_7_8.BaudRate)
  return baudrate_;
}
inline void IEC60044_7_8::set_baudrate(::google::protobuf::int32 value) {
  
  baudrate_ = value;
  // @@protoc_insertion_point(field_set:hqyIEC60044_7_8_Setting.IEC60044_7_8.BaudRate)
}

// double RatedProtectCurrent = 9;
inline void IEC60044_7_8::clear_ratedprotectcurrent() {
  ratedprotectcurrent_ = 0;
}
inline double IEC60044_7_8::ratedprotectcurrent() const {
  // @@protoc_insertion_point(field_get:hqyIEC60044_7_8_Setting.IEC60044_7_8.RatedProtectCurrent)
  return ratedprotectcurrent_;
}
inline void IEC60044_7_8::set_ratedprotectcurrent(double value) {
  
  ratedprotectcurrent_ = value;
  // @@protoc_insertion_point(field_set:hqyIEC60044_7_8_Setting.IEC60044_7_8.RatedProtectCurrent)
}

// double RatedZeroSeqCurrent = 10;
inline void IEC60044_7_8::clear_ratedzeroseqcurrent() {
  ratedzeroseqcurrent_ = 0;
}
inline double IEC60044_7_8::ratedzeroseqcurrent() const {
  // @@protoc_insertion_point(field_get:hqyIEC60044_7_8_Setting.IEC60044_7_8.RatedZeroSeqCurrent)
  return ratedzeroseqcurrent_;
}
inline void IEC60044_7_8::set_ratedzeroseqcurrent(double value) {
  
  ratedzeroseqcurrent_ = value;
  // @@protoc_insertion_point(field_set:hqyIEC60044_7_8_Setting.IEC60044_7_8.RatedZeroSeqCurrent)
}

// double RatedPhaseVoltage = 11;
inline void IEC60044_7_8::clear_ratedphasevoltage() {
  ratedphasevoltage_ = 0;
}
inline double IEC60044_7_8::ratedphasevoltage() const {
  // @@protoc_insertion_point(field_get:hqyIEC60044_7_8_Setting.IEC60044_7_8.RatedPhaseVoltage)
  return ratedphasevoltage_;
}
inline void IEC60044_7_8::set_ratedphasevoltage(double value) {
  
  ratedphasevoltage_ = value;
  // @@protoc_insertion_point(field_set:hqyIEC60044_7_8_Setting.IEC60044_7_8.RatedPhaseVoltage)
}

// bool OutputIsPrimary = 12;
inline void IEC60044_7_8::clear_outputisprimary() {
  outputisprimary_ = false;
}
inline bool IEC60044_7_8::outputisprimary() const {
  // @@protoc_insertion_point(field_get:hqyIEC60044_7_8_Setting.IEC60044_7_8.OutputIsPrimary)
  return outputisprimary_;
}
inline void IEC60044_7_8::set_outputisprimary(bool value) {
  
  outputisprimary_ = value;
  // @@protoc_insertion_point(field_set:hqyIEC60044_7_8_Setting.IEC60044_7_8.OutputIsPrimary)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace hqyIEC60044_7_8_Setting

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::hqyIEC60044_7_8_Setting::Channel_Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::hqyIEC60044_7_8_Setting::Channel_Type>() {
  return ::hqyIEC60044_7_8_Setting::Channel_Type_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_hqyiec6004478_2eproto__INCLUDED
