// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hqySetting.proto

#ifndef PROTOBUF_hqySetting_2eproto__INCLUDED
#define PROTOBUF_hqySetting_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace hqySettingPackage {
class ComSetting;
class ComSettingDefaultTypeInternal;
extern ComSettingDefaultTypeInternal _ComSetting_default_instance_;
class Setting;
class SettingDefaultTypeInternal;
extern SettingDefaultTypeInternal _Setting_default_instance_;
}  // namespace hqySettingPackage

namespace hqySettingPackage {

namespace protobuf_hqySetting_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_hqySetting_2eproto

enum SettingType {
  ST_BinarySetting = 0,
  ST_ComSetting = 1,
  SettingType_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  SettingType_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool SettingType_IsValid(int value);
const SettingType SettingType_MIN = ST_BinarySetting;
const SettingType SettingType_MAX = ST_ComSetting;
const int SettingType_ARRAYSIZE = SettingType_MAX + 1;

const ::google::protobuf::EnumDescriptor* SettingType_descriptor();
inline const ::std::string& SettingType_Name(SettingType value) {
  return ::google::protobuf::internal::NameOfEnum(
    SettingType_descriptor(), value);
}
inline bool SettingType_Parse(
    const ::std::string& name, SettingType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SettingType>(
    SettingType_descriptor(), name, value);
}
// ===================================================================

class ComSetting : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hqySettingPackage.ComSetting) */ {
 public:
  ComSetting();
  virtual ~ComSetting();

  ComSetting(const ComSetting& from);

  inline ComSetting& operator=(const ComSetting& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ComSetting& default_instance();

  static inline const ComSetting* internal_default_instance() {
    return reinterpret_cast<const ComSetting*>(
               &_ComSetting_default_instance_);
  }

  void Swap(ComSetting* other);

  // implements Message ----------------------------------------------

  inline ComSetting* New() const PROTOBUF_FINAL { return New(NULL); }

  ComSetting* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ComSetting& from);
  void MergeFrom(const ComSetting& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ComSetting* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string strIP = 1;
  void clear_strip();
  static const int kStrIPFieldNumber = 1;
  const ::std::string& strip() const;
  void set_strip(const ::std::string& value);
  #if LANG_CXX11
  void set_strip(::std::string&& value);
  #endif
  void set_strip(const char* value);
  void set_strip(const char* value, size_t size);
  ::std::string* mutable_strip();
  ::std::string* release_strip();
  void set_allocated_strip(::std::string* strip);

  // uint32 nPort = 2;
  void clear_nport();
  static const int kNPortFieldNumber = 2;
  ::google::protobuf::uint32 nport() const;
  void set_nport(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:hqySettingPackage.ComSetting)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr strip_;
  ::google::protobuf::uint32 nport_;
  mutable int _cached_size_;
  friend struct  protobuf_hqySetting_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Setting : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hqySettingPackage.Setting) */ {
 public:
  Setting();
  virtual ~Setting();

  Setting(const Setting& from);

  inline Setting& operator=(const Setting& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Setting& default_instance();

  static inline const Setting* internal_default_instance() {
    return reinterpret_cast<const Setting*>(
               &_Setting_default_instance_);
  }

  void Swap(Setting* other);

  // implements Message ----------------------------------------------

  inline Setting* New() const PROTOBUF_FINAL { return New(NULL); }

  Setting* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Setting& from);
  void MergeFrom(const Setting& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Setting* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .hqySettingPackage.ComSetting oComSetting = 2;
  bool has_ocomsetting() const;
  void clear_ocomsetting();
  static const int kOComSettingFieldNumber = 2;
  const ::hqySettingPackage::ComSetting& ocomsetting() const;
  ::hqySettingPackage::ComSetting* mutable_ocomsetting();
  ::hqySettingPackage::ComSetting* release_ocomsetting();
  void set_allocated_ocomsetting(::hqySettingPackage::ComSetting* ocomsetting);

  // .hqySettingPackage.SettingType nType = 1;
  void clear_ntype();
  static const int kNTypeFieldNumber = 1;
  ::hqySettingPackage::SettingType ntype() const;
  void set_ntype(::hqySettingPackage::SettingType value);

  // @@protoc_insertion_point(class_scope:hqySettingPackage.Setting)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::hqySettingPackage::ComSetting* ocomsetting_;
  int ntype_;
  mutable int _cached_size_;
  friend struct  protobuf_hqySetting_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ComSetting

// string strIP = 1;
inline void ComSetting::clear_strip() {
  strip_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ComSetting::strip() const {
  // @@protoc_insertion_point(field_get:hqySettingPackage.ComSetting.strIP)
  return strip_.GetNoArena();
}
inline void ComSetting::set_strip(const ::std::string& value) {
  
  strip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hqySettingPackage.ComSetting.strIP)
}
#if LANG_CXX11
inline void ComSetting::set_strip(::std::string&& value) {
  
  strip_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hqySettingPackage.ComSetting.strIP)
}
#endif
inline void ComSetting::set_strip(const char* value) {
  
  strip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hqySettingPackage.ComSetting.strIP)
}
inline void ComSetting::set_strip(const char* value, size_t size) {
  
  strip_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hqySettingPackage.ComSetting.strIP)
}
inline ::std::string* ComSetting::mutable_strip() {
  
  // @@protoc_insertion_point(field_mutable:hqySettingPackage.ComSetting.strIP)
  return strip_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ComSetting::release_strip() {
  // @@protoc_insertion_point(field_release:hqySettingPackage.ComSetting.strIP)
  
  return strip_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ComSetting::set_allocated_strip(::std::string* strip) {
  if (strip != NULL) {
    
  } else {
    
  }
  strip_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), strip);
  // @@protoc_insertion_point(field_set_allocated:hqySettingPackage.ComSetting.strIP)
}

// uint32 nPort = 2;
inline void ComSetting::clear_nport() {
  nport_ = 0u;
}
inline ::google::protobuf::uint32 ComSetting::nport() const {
  // @@protoc_insertion_point(field_get:hqySettingPackage.ComSetting.nPort)
  return nport_;
}
inline void ComSetting::set_nport(::google::protobuf::uint32 value) {
  
  nport_ = value;
  // @@protoc_insertion_point(field_set:hqySettingPackage.ComSetting.nPort)
}

// -------------------------------------------------------------------

// Setting

// .hqySettingPackage.SettingType nType = 1;
inline void Setting::clear_ntype() {
  ntype_ = 0;
}
inline ::hqySettingPackage::SettingType Setting::ntype() const {
  // @@protoc_insertion_point(field_get:hqySettingPackage.Setting.nType)
  return static_cast< ::hqySettingPackage::SettingType >(ntype_);
}
inline void Setting::set_ntype(::hqySettingPackage::SettingType value) {
  
  ntype_ = value;
  // @@protoc_insertion_point(field_set:hqySettingPackage.Setting.nType)
}

// .hqySettingPackage.ComSetting oComSetting = 2;
inline bool Setting::has_ocomsetting() const {
  return this != internal_default_instance() && ocomsetting_ != NULL;
}
inline void Setting::clear_ocomsetting() {
  if (GetArenaNoVirtual() == NULL && ocomsetting_ != NULL) delete ocomsetting_;
  ocomsetting_ = NULL;
}
inline const ::hqySettingPackage::ComSetting& Setting::ocomsetting() const {
  // @@protoc_insertion_point(field_get:hqySettingPackage.Setting.oComSetting)
  return ocomsetting_ != NULL ? *ocomsetting_
                         : *::hqySettingPackage::ComSetting::internal_default_instance();
}
inline ::hqySettingPackage::ComSetting* Setting::mutable_ocomsetting() {
  
  if (ocomsetting_ == NULL) {
    ocomsetting_ = new ::hqySettingPackage::ComSetting;
  }
  // @@protoc_insertion_point(field_mutable:hqySettingPackage.Setting.oComSetting)
  return ocomsetting_;
}
inline ::hqySettingPackage::ComSetting* Setting::release_ocomsetting() {
  // @@protoc_insertion_point(field_release:hqySettingPackage.Setting.oComSetting)
  
  ::hqySettingPackage::ComSetting* temp = ocomsetting_;
  ocomsetting_ = NULL;
  return temp;
}
inline void Setting::set_allocated_ocomsetting(::hqySettingPackage::ComSetting* ocomsetting) {
  delete ocomsetting_;
  ocomsetting_ = ocomsetting;
  if (ocomsetting) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:hqySettingPackage.Setting.oComSetting)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace hqySettingPackage

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::hqySettingPackage::SettingType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::hqySettingPackage::SettingType>() {
  return ::hqySettingPackage::SettingType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_hqySetting_2eproto__INCLUDED
