// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OutPutCommon.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "OutPutCommon.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace OutPutCommon {
class GradientParaDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<GradientPara> {
} _GradientPara_default_instance_;
class chanelparaDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<chanelpara> {
} _chanelpara_default_instance_;
class acanalogparaDefaultTypeInternal : public ::google::protobuf::internal::ExplicitlyConstructed<acanalogpara> {
} _acanalogpara_default_instance_;

namespace protobuf_OutPutCommon_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[3];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[2];

}  // namespace

const ::google::protobuf::uint32 TableStruct::offsets[] = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GradientPara, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GradientPara, ivar_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GradientPara, itype_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GradientPara, fstep_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GradientPara, fsteptime_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GradientPara, fstart_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GradientPara, fend_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GradientPara, nharm_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(chanelpara, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(chanelpara, famptitude_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(chanelpara, fphase_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(chanelpara, ffre_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(acanalogpara, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(acanalogpara, analogcurrentchanelvalue_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(acanalogpara, analogvoltchangelvalue_),
};

static const ::google::protobuf::internal::MigrationSchema schemas[] = {
  { 0, -1, sizeof(GradientPara)},
  { 11, -1, sizeof(chanelpara)},
  { 18, -1, sizeof(acanalogpara)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_GradientPara_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_chanelpara_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_acanalogpara_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "OutPutCommon.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

}  // namespace

void TableStruct::Shutdown() {
  _GradientPara_default_instance_.Shutdown();
  delete file_level_metadata[0].reflection;
  _chanelpara_default_instance_.Shutdown();
  delete file_level_metadata[1].reflection;
  _acanalogpara_default_instance_.Shutdown();
  delete file_level_metadata[2].reflection;
}

void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _GradientPara_default_instance_.DefaultConstruct();
  _chanelpara_default_instance_.DefaultConstruct();
  _acanalogpara_default_instance_.DefaultConstruct();
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] = {
      "\n\022OutPutCommon.proto\022\014OutPutCommon\"\257\001\n\014G"
      "radientPara\022%\n\004iVar\030\001 \001(\0162\027.OutPutCommon"
      ".para_type\022)\n\005iType\030\002 \001(\0162\032.OutPutCommon"
      ".changed_type\022\r\n\005fStep\030\003 \001(\002\022\021\n\tfStepTim"
      "e\030\004 \001(\002\022\016\n\006fStart\030\005 \001(\002\022\014\n\004fEnd\030\006 \001(\002\022\r\n"
      "\005nHarm\030\007 \001(\r\">\n\nchanelpara\022\022\n\nfamptitude"
      "\030\001 \001(\002\022\016\n\006fphase\030\002 \001(\002\022\014\n\004ffre\030\003 \001(\002\"\204\001\n"
      "\014acanalogpara\022:\n\030analogcurrentchanelvalu"
      "e\030\001 \003(\0132\030.OutPutCommon.chanelpara\0228\n\026ana"
      "logvoltchangelvalue\030\002 \003(\0132\030.OutPutCommon"
      ".chanelpara*\206\003\n\tpara_type\022\014\n\010va1_type\020\000\022"
      "\014\n\010vb1_type\020\001\022\014\n\010vc1_type\020\002\022\r\n\tvab1_type"
      "\020\004\022\r\n\tvbc1_type\020\005\022\r\n\tvca1_type\020\006\022\016\n\nvabc"
      "1_type\020\007\022\014\n\010va2_type\020\010\022\014\n\010vb2_type\020\t\022\014\n\010"
      "vc2_type\020\n\022\016\n\nvabc2_type\020\013\022\014\n\010ia1_type\020\014"
      "\022\014\n\010ib1_type\020\r\022\014\n\010ic1_type\020\016\022\r\n\tiab1_typ"
      "e\020\017\022\r\n\tibc1_type\020\020\022\r\n\tica1_type\020\021\022\016\n\niab"
      "c1_type\020\022\022\014\n\010ia2_type\020\023\022\014\n\010ib2_type\020\024\022\014\n"
      "\010ic2_type\020\025\022\016\n\niabc2_type\020\026\022\r\n\tvall_type"
      "\020\027\022\r\n\tiall_type\020\030\022\014\n\010vdc_type\020\031\022\013\n\007vz_ty"
      "pe\020\032*A\n\014changed_type\022\022\n\016amplitude_type\020\000"
      "\022\017\n\013phasor_type\020\001\022\014\n\010fre_type\020\002b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 879);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "OutPutCommon.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&TableStruct::Shutdown);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_OutPutCommon_2eproto

const ::google::protobuf::EnumDescriptor* para_type_descriptor() {
  protobuf_OutPutCommon_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_OutPutCommon_2eproto::file_level_enum_descriptors[0];
}
bool para_type_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
      return true;
    default:
      return false;
  }
}

const ::google::protobuf::EnumDescriptor* changed_type_descriptor() {
  protobuf_OutPutCommon_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_OutPutCommon_2eproto::file_level_enum_descriptors[1];
}
bool changed_type_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GradientPara::kIVarFieldNumber;
const int GradientPara::kITypeFieldNumber;
const int GradientPara::kFStepFieldNumber;
const int GradientPara::kFStepTimeFieldNumber;
const int GradientPara::kFStartFieldNumber;
const int GradientPara::kFEndFieldNumber;
const int GradientPara::kNHarmFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GradientPara::GradientPara()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_OutPutCommon_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:OutPutCommon.GradientPara)
}
GradientPara::GradientPara(const GradientPara& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&ivar_, &from.ivar_,
    reinterpret_cast<char*>(&nharm_) -
    reinterpret_cast<char*>(&ivar_) + sizeof(nharm_));
  // @@protoc_insertion_point(copy_constructor:OutPutCommon.GradientPara)
}

void GradientPara::SharedCtor() {
  ::memset(&ivar_, 0, reinterpret_cast<char*>(&nharm_) -
    reinterpret_cast<char*>(&ivar_) + sizeof(nharm_));
  _cached_size_ = 0;
}

GradientPara::~GradientPara() {
  // @@protoc_insertion_point(destructor:OutPutCommon.GradientPara)
  SharedDtor();
}

void GradientPara::SharedDtor() {
}

void GradientPara::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GradientPara::descriptor() {
  protobuf_OutPutCommon_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_OutPutCommon_2eproto::file_level_metadata[0].descriptor;
}

const GradientPara& GradientPara::default_instance() {
  protobuf_OutPutCommon_2eproto::InitDefaults();
  return *internal_default_instance();
}

GradientPara* GradientPara::New(::google::protobuf::Arena* arena) const {
  GradientPara* n = new GradientPara;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void GradientPara::Clear() {
// @@protoc_insertion_point(message_clear_start:OutPutCommon.GradientPara)
  ::memset(&ivar_, 0, reinterpret_cast<char*>(&nharm_) -
    reinterpret_cast<char*>(&ivar_) + sizeof(nharm_));
}

bool GradientPara::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:OutPutCommon.GradientPara)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .OutPutCommon.para_type iVar = 1;
      case 1: {
        if (tag == 8u) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_ivar(static_cast< ::OutPutCommon::para_type >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .OutPutCommon.changed_type iType = 2;
      case 2: {
        if (tag == 16u) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_itype(static_cast< ::OutPutCommon::changed_type >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float fStep = 3;
      case 3: {
        if (tag == 29u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &fstep_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float fStepTime = 4;
      case 4: {
        if (tag == 37u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &fsteptime_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float fStart = 5;
      case 5: {
        if (tag == 45u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &fstart_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float fEnd = 6;
      case 6: {
        if (tag == 53u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &fend_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 nHarm = 7;
      case 7: {
        if (tag == 56u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &nharm_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:OutPutCommon.GradientPara)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:OutPutCommon.GradientPara)
  return false;
#undef DO_
}

void GradientPara::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:OutPutCommon.GradientPara)
  // .OutPutCommon.para_type iVar = 1;
  if (this->ivar() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->ivar(), output);
  }

  // .OutPutCommon.changed_type iType = 2;
  if (this->itype() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->itype(), output);
  }

  // float fStep = 3;
  if (this->fstep() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->fstep(), output);
  }

  // float fStepTime = 4;
  if (this->fsteptime() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->fsteptime(), output);
  }

  // float fStart = 5;
  if (this->fstart() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->fstart(), output);
  }

  // float fEnd = 6;
  if (this->fend() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(6, this->fend(), output);
  }

  // uint32 nHarm = 7;
  if (this->nharm() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(7, this->nharm(), output);
  }

  // @@protoc_insertion_point(serialize_end:OutPutCommon.GradientPara)
}

::google::protobuf::uint8* GradientPara::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:OutPutCommon.GradientPara)
  // .OutPutCommon.para_type iVar = 1;
  if (this->ivar() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->ivar(), target);
  }

  // .OutPutCommon.changed_type iType = 2;
  if (this->itype() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      2, this->itype(), target);
  }

  // float fStep = 3;
  if (this->fstep() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->fstep(), target);
  }

  // float fStepTime = 4;
  if (this->fsteptime() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->fsteptime(), target);
  }

  // float fStart = 5;
  if (this->fstart() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->fstart(), target);
  }

  // float fEnd = 6;
  if (this->fend() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(6, this->fend(), target);
  }

  // uint32 nHarm = 7;
  if (this->nharm() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(7, this->nharm(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:OutPutCommon.GradientPara)
  return target;
}

size_t GradientPara::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OutPutCommon.GradientPara)
  size_t total_size = 0;

  // .OutPutCommon.para_type iVar = 1;
  if (this->ivar() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->ivar());
  }

  // .OutPutCommon.changed_type iType = 2;
  if (this->itype() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->itype());
  }

  // float fStep = 3;
  if (this->fstep() != 0) {
    total_size += 1 + 4;
  }

  // float fStepTime = 4;
  if (this->fsteptime() != 0) {
    total_size += 1 + 4;
  }

  // float fStart = 5;
  if (this->fstart() != 0) {
    total_size += 1 + 4;
  }

  // float fEnd = 6;
  if (this->fend() != 0) {
    total_size += 1 + 4;
  }

  // uint32 nHarm = 7;
  if (this->nharm() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->nharm());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GradientPara::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:OutPutCommon.GradientPara)
  GOOGLE_DCHECK_NE(&from, this);
  const GradientPara* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GradientPara>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:OutPutCommon.GradientPara)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:OutPutCommon.GradientPara)
    MergeFrom(*source);
  }
}

void GradientPara::MergeFrom(const GradientPara& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:OutPutCommon.GradientPara)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.ivar() != 0) {
    set_ivar(from.ivar());
  }
  if (from.itype() != 0) {
    set_itype(from.itype());
  }
  if (from.fstep() != 0) {
    set_fstep(from.fstep());
  }
  if (from.fsteptime() != 0) {
    set_fsteptime(from.fsteptime());
  }
  if (from.fstart() != 0) {
    set_fstart(from.fstart());
  }
  if (from.fend() != 0) {
    set_fend(from.fend());
  }
  if (from.nharm() != 0) {
    set_nharm(from.nharm());
  }
}

void GradientPara::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:OutPutCommon.GradientPara)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GradientPara::CopyFrom(const GradientPara& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OutPutCommon.GradientPara)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GradientPara::IsInitialized() const {
  return true;
}

void GradientPara::Swap(GradientPara* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GradientPara::InternalSwap(GradientPara* other) {
  std::swap(ivar_, other->ivar_);
  std::swap(itype_, other->itype_);
  std::swap(fstep_, other->fstep_);
  std::swap(fsteptime_, other->fsteptime_);
  std::swap(fstart_, other->fstart_);
  std::swap(fend_, other->fend_);
  std::swap(nharm_, other->nharm_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata GradientPara::GetMetadata() const {
  protobuf_OutPutCommon_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_OutPutCommon_2eproto::file_level_metadata[0];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// GradientPara

// .OutPutCommon.para_type iVar = 1;
void GradientPara::clear_ivar() {
  ivar_ = 0;
}
::OutPutCommon::para_type GradientPara::ivar() const {
  // @@protoc_insertion_point(field_get:OutPutCommon.GradientPara.iVar)
  return static_cast< ::OutPutCommon::para_type >(ivar_);
}
void GradientPara::set_ivar(::OutPutCommon::para_type value) {
  
  ivar_ = value;
  // @@protoc_insertion_point(field_set:OutPutCommon.GradientPara.iVar)
}

// .OutPutCommon.changed_type iType = 2;
void GradientPara::clear_itype() {
  itype_ = 0;
}
::OutPutCommon::changed_type GradientPara::itype() const {
  // @@protoc_insertion_point(field_get:OutPutCommon.GradientPara.iType)
  return static_cast< ::OutPutCommon::changed_type >(itype_);
}
void GradientPara::set_itype(::OutPutCommon::changed_type value) {
  
  itype_ = value;
  // @@protoc_insertion_point(field_set:OutPutCommon.GradientPara.iType)
}

// float fStep = 3;
void GradientPara::clear_fstep() {
  fstep_ = 0;
}
float GradientPara::fstep() const {
  // @@protoc_insertion_point(field_get:OutPutCommon.GradientPara.fStep)
  return fstep_;
}
void GradientPara::set_fstep(float value) {
  
  fstep_ = value;
  // @@protoc_insertion_point(field_set:OutPutCommon.GradientPara.fStep)
}

// float fStepTime = 4;
void GradientPara::clear_fsteptime() {
  fsteptime_ = 0;
}
float GradientPara::fsteptime() const {
  // @@protoc_insertion_point(field_get:OutPutCommon.GradientPara.fStepTime)
  return fsteptime_;
}
void GradientPara::set_fsteptime(float value) {
  
  fsteptime_ = value;
  // @@protoc_insertion_point(field_set:OutPutCommon.GradientPara.fStepTime)
}

// float fStart = 5;
void GradientPara::clear_fstart() {
  fstart_ = 0;
}
float GradientPara::fstart() const {
  // @@protoc_insertion_point(field_get:OutPutCommon.GradientPara.fStart)
  return fstart_;
}
void GradientPara::set_fstart(float value) {
  
  fstart_ = value;
  // @@protoc_insertion_point(field_set:OutPutCommon.GradientPara.fStart)
}

// float fEnd = 6;
void GradientPara::clear_fend() {
  fend_ = 0;
}
float GradientPara::fend() const {
  // @@protoc_insertion_point(field_get:OutPutCommon.GradientPara.fEnd)
  return fend_;
}
void GradientPara::set_fend(float value) {
  
  fend_ = value;
  // @@protoc_insertion_point(field_set:OutPutCommon.GradientPara.fEnd)
}

// uint32 nHarm = 7;
void GradientPara::clear_nharm() {
  nharm_ = 0u;
}
::google::protobuf::uint32 GradientPara::nharm() const {
  // @@protoc_insertion_point(field_get:OutPutCommon.GradientPara.nHarm)
  return nharm_;
}
void GradientPara::set_nharm(::google::protobuf::uint32 value) {
  
  nharm_ = value;
  // @@protoc_insertion_point(field_set:OutPutCommon.GradientPara.nHarm)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int chanelpara::kFamptitudeFieldNumber;
const int chanelpara::kFphaseFieldNumber;
const int chanelpara::kFfreFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

chanelpara::chanelpara()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_OutPutCommon_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:OutPutCommon.chanelpara)
}
chanelpara::chanelpara(const chanelpara& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&famptitude_, &from.famptitude_,
    reinterpret_cast<char*>(&ffre_) -
    reinterpret_cast<char*>(&famptitude_) + sizeof(ffre_));
  // @@protoc_insertion_point(copy_constructor:OutPutCommon.chanelpara)
}

void chanelpara::SharedCtor() {
  ::memset(&famptitude_, 0, reinterpret_cast<char*>(&ffre_) -
    reinterpret_cast<char*>(&famptitude_) + sizeof(ffre_));
  _cached_size_ = 0;
}

chanelpara::~chanelpara() {
  // @@protoc_insertion_point(destructor:OutPutCommon.chanelpara)
  SharedDtor();
}

void chanelpara::SharedDtor() {
}

void chanelpara::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* chanelpara::descriptor() {
  protobuf_OutPutCommon_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_OutPutCommon_2eproto::file_level_metadata[1].descriptor;
}

const chanelpara& chanelpara::default_instance() {
  protobuf_OutPutCommon_2eproto::InitDefaults();
  return *internal_default_instance();
}

chanelpara* chanelpara::New(::google::protobuf::Arena* arena) const {
  chanelpara* n = new chanelpara;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void chanelpara::Clear() {
// @@protoc_insertion_point(message_clear_start:OutPutCommon.chanelpara)
  ::memset(&famptitude_, 0, reinterpret_cast<char*>(&ffre_) -
    reinterpret_cast<char*>(&famptitude_) + sizeof(ffre_));
}

bool chanelpara::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:OutPutCommon.chanelpara)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // float famptitude = 1;
      case 1: {
        if (tag == 13u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &famptitude_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float fphase = 2;
      case 2: {
        if (tag == 21u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &fphase_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float ffre = 3;
      case 3: {
        if (tag == 29u) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &ffre_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:OutPutCommon.chanelpara)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:OutPutCommon.chanelpara)
  return false;
#undef DO_
}

void chanelpara::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:OutPutCommon.chanelpara)
  // float famptitude = 1;
  if (this->famptitude() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->famptitude(), output);
  }

  // float fphase = 2;
  if (this->fphase() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->fphase(), output);
  }

  // float ffre = 3;
  if (this->ffre() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->ffre(), output);
  }

  // @@protoc_insertion_point(serialize_end:OutPutCommon.chanelpara)
}

::google::protobuf::uint8* chanelpara::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:OutPutCommon.chanelpara)
  // float famptitude = 1;
  if (this->famptitude() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->famptitude(), target);
  }

  // float fphase = 2;
  if (this->fphase() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->fphase(), target);
  }

  // float ffre = 3;
  if (this->ffre() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->ffre(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:OutPutCommon.chanelpara)
  return target;
}

size_t chanelpara::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OutPutCommon.chanelpara)
  size_t total_size = 0;

  // float famptitude = 1;
  if (this->famptitude() != 0) {
    total_size += 1 + 4;
  }

  // float fphase = 2;
  if (this->fphase() != 0) {
    total_size += 1 + 4;
  }

  // float ffre = 3;
  if (this->ffre() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void chanelpara::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:OutPutCommon.chanelpara)
  GOOGLE_DCHECK_NE(&from, this);
  const chanelpara* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const chanelpara>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:OutPutCommon.chanelpara)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:OutPutCommon.chanelpara)
    MergeFrom(*source);
  }
}

void chanelpara::MergeFrom(const chanelpara& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:OutPutCommon.chanelpara)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.famptitude() != 0) {
    set_famptitude(from.famptitude());
  }
  if (from.fphase() != 0) {
    set_fphase(from.fphase());
  }
  if (from.ffre() != 0) {
    set_ffre(from.ffre());
  }
}

void chanelpara::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:OutPutCommon.chanelpara)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void chanelpara::CopyFrom(const chanelpara& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OutPutCommon.chanelpara)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool chanelpara::IsInitialized() const {
  return true;
}

void chanelpara::Swap(chanelpara* other) {
  if (other == this) return;
  InternalSwap(other);
}
void chanelpara::InternalSwap(chanelpara* other) {
  std::swap(famptitude_, other->famptitude_);
  std::swap(fphase_, other->fphase_);
  std::swap(ffre_, other->ffre_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata chanelpara::GetMetadata() const {
  protobuf_OutPutCommon_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_OutPutCommon_2eproto::file_level_metadata[1];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// chanelpara

// float famptitude = 1;
void chanelpara::clear_famptitude() {
  famptitude_ = 0;
}
float chanelpara::famptitude() const {
  // @@protoc_insertion_point(field_get:OutPutCommon.chanelpara.famptitude)
  return famptitude_;
}
void chanelpara::set_famptitude(float value) {
  
  famptitude_ = value;
  // @@protoc_insertion_point(field_set:OutPutCommon.chanelpara.famptitude)
}

// float fphase = 2;
void chanelpara::clear_fphase() {
  fphase_ = 0;
}
float chanelpara::fphase() const {
  // @@protoc_insertion_point(field_get:OutPutCommon.chanelpara.fphase)
  return fphase_;
}
void chanelpara::set_fphase(float value) {
  
  fphase_ = value;
  // @@protoc_insertion_point(field_set:OutPutCommon.chanelpara.fphase)
}

// float ffre = 3;
void chanelpara::clear_ffre() {
  ffre_ = 0;
}
float chanelpara::ffre() const {
  // @@protoc_insertion_point(field_get:OutPutCommon.chanelpara.ffre)
  return ffre_;
}
void chanelpara::set_ffre(float value) {
  
  ffre_ = value;
  // @@protoc_insertion_point(field_set:OutPutCommon.chanelpara.ffre)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int acanalogpara::kAnalogcurrentchanelvalueFieldNumber;
const int acanalogpara::kAnalogvoltchangelvalueFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

acanalogpara::acanalogpara()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_OutPutCommon_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:OutPutCommon.acanalogpara)
}
acanalogpara::acanalogpara(const acanalogpara& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      analogcurrentchanelvalue_(from.analogcurrentchanelvalue_),
      analogvoltchangelvalue_(from.analogvoltchangelvalue_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:OutPutCommon.acanalogpara)
}

void acanalogpara::SharedCtor() {
  _cached_size_ = 0;
}

acanalogpara::~acanalogpara() {
  // @@protoc_insertion_point(destructor:OutPutCommon.acanalogpara)
  SharedDtor();
}

void acanalogpara::SharedDtor() {
}

void acanalogpara::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* acanalogpara::descriptor() {
  protobuf_OutPutCommon_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_OutPutCommon_2eproto::file_level_metadata[2].descriptor;
}

const acanalogpara& acanalogpara::default_instance() {
  protobuf_OutPutCommon_2eproto::InitDefaults();
  return *internal_default_instance();
}

acanalogpara* acanalogpara::New(::google::protobuf::Arena* arena) const {
  acanalogpara* n = new acanalogpara;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void acanalogpara::Clear() {
// @@protoc_insertion_point(message_clear_start:OutPutCommon.acanalogpara)
  analogcurrentchanelvalue_.Clear();
  analogvoltchangelvalue_.Clear();
}

bool acanalogpara::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:OutPutCommon.acanalogpara)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .OutPutCommon.chanelpara analogcurrentchanelvalue = 1;
      case 1: {
        if (tag == 10u) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_analogcurrentchanelvalue()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      // repeated .OutPutCommon.chanelpara analogvoltchangelvalue = 2;
      case 2: {
        if (tag == 18u) {
          DO_(input->IncrementRecursionDepth());
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_analogvoltchangelvalue()));
        } else {
          goto handle_unusual;
        }
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:OutPutCommon.acanalogpara)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:OutPutCommon.acanalogpara)
  return false;
#undef DO_
}

void acanalogpara::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:OutPutCommon.acanalogpara)
  // repeated .OutPutCommon.chanelpara analogcurrentchanelvalue = 1;
  for (unsigned int i = 0, n = this->analogcurrentchanelvalue_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->analogcurrentchanelvalue(i), output);
  }

  // repeated .OutPutCommon.chanelpara analogvoltchangelvalue = 2;
  for (unsigned int i = 0, n = this->analogvoltchangelvalue_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->analogvoltchangelvalue(i), output);
  }

  // @@protoc_insertion_point(serialize_end:OutPutCommon.acanalogpara)
}

::google::protobuf::uint8* acanalogpara::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic;  // Unused
  // @@protoc_insertion_point(serialize_to_array_start:OutPutCommon.acanalogpara)
  // repeated .OutPutCommon.chanelpara analogcurrentchanelvalue = 1;
  for (unsigned int i = 0, n = this->analogcurrentchanelvalue_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->analogcurrentchanelvalue(i), false, target);
  }

  // repeated .OutPutCommon.chanelpara analogvoltchangelvalue = 2;
  for (unsigned int i = 0, n = this->analogvoltchangelvalue_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->analogvoltchangelvalue(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:OutPutCommon.acanalogpara)
  return target;
}

size_t acanalogpara::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:OutPutCommon.acanalogpara)
  size_t total_size = 0;

  // repeated .OutPutCommon.chanelpara analogcurrentchanelvalue = 1;
  {
    unsigned int count = this->analogcurrentchanelvalue_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->analogcurrentchanelvalue(i));
    }
  }

  // repeated .OutPutCommon.chanelpara analogvoltchangelvalue = 2;
  {
    unsigned int count = this->analogvoltchangelvalue_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->analogvoltchangelvalue(i));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void acanalogpara::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:OutPutCommon.acanalogpara)
  GOOGLE_DCHECK_NE(&from, this);
  const acanalogpara* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const acanalogpara>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:OutPutCommon.acanalogpara)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:OutPutCommon.acanalogpara)
    MergeFrom(*source);
  }
}

void acanalogpara::MergeFrom(const acanalogpara& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:OutPutCommon.acanalogpara)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  analogcurrentchanelvalue_.MergeFrom(from.analogcurrentchanelvalue_);
  analogvoltchangelvalue_.MergeFrom(from.analogvoltchangelvalue_);
}

void acanalogpara::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:OutPutCommon.acanalogpara)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void acanalogpara::CopyFrom(const acanalogpara& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:OutPutCommon.acanalogpara)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool acanalogpara::IsInitialized() const {
  return true;
}

void acanalogpara::Swap(acanalogpara* other) {
  if (other == this) return;
  InternalSwap(other);
}
void acanalogpara::InternalSwap(acanalogpara* other) {
  analogcurrentchanelvalue_.UnsafeArenaSwap(&other->analogcurrentchanelvalue_);
  analogvoltchangelvalue_.UnsafeArenaSwap(&other->analogvoltchangelvalue_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata acanalogpara::GetMetadata() const {
  protobuf_OutPutCommon_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_OutPutCommon_2eproto::file_level_metadata[2];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// acanalogpara

// repeated .OutPutCommon.chanelpara analogcurrentchanelvalue = 1;
int acanalogpara::analogcurrentchanelvalue_size() const {
  return analogcurrentchanelvalue_.size();
}
void acanalogpara::clear_analogcurrentchanelvalue() {
  analogcurrentchanelvalue_.Clear();
}
const ::OutPutCommon::chanelpara& acanalogpara::analogcurrentchanelvalue(int index) const {
  // @@protoc_insertion_point(field_get:OutPutCommon.acanalogpara.analogcurrentchanelvalue)
  return analogcurrentchanelvalue_.Get(index);
}
::OutPutCommon::chanelpara* acanalogpara::mutable_analogcurrentchanelvalue(int index) {
  // @@protoc_insertion_point(field_mutable:OutPutCommon.acanalogpara.analogcurrentchanelvalue)
  return analogcurrentchanelvalue_.Mutable(index);
}
::OutPutCommon::chanelpara* acanalogpara::add_analogcurrentchanelvalue() {
  // @@protoc_insertion_point(field_add:OutPutCommon.acanalogpara.analogcurrentchanelvalue)
  return analogcurrentchanelvalue_.Add();
}
::google::protobuf::RepeatedPtrField< ::OutPutCommon::chanelpara >*
acanalogpara::mutable_analogcurrentchanelvalue() {
  // @@protoc_insertion_point(field_mutable_list:OutPutCommon.acanalogpara.analogcurrentchanelvalue)
  return &analogcurrentchanelvalue_;
}
const ::google::protobuf::RepeatedPtrField< ::OutPutCommon::chanelpara >&
acanalogpara::analogcurrentchanelvalue() const {
  // @@protoc_insertion_point(field_list:OutPutCommon.acanalogpara.analogcurrentchanelvalue)
  return analogcurrentchanelvalue_;
}

// repeated .OutPutCommon.chanelpara analogvoltchangelvalue = 2;
int acanalogpara::analogvoltchangelvalue_size() const {
  return analogvoltchangelvalue_.size();
}
void acanalogpara::clear_analogvoltchangelvalue() {
  analogvoltchangelvalue_.Clear();
}
const ::OutPutCommon::chanelpara& acanalogpara::analogvoltchangelvalue(int index) const {
  // @@protoc_insertion_point(field_get:OutPutCommon.acanalogpara.analogvoltchangelvalue)
  return analogvoltchangelvalue_.Get(index);
}
::OutPutCommon::chanelpara* acanalogpara::mutable_analogvoltchangelvalue(int index) {
  // @@protoc_insertion_point(field_mutable:OutPutCommon.acanalogpara.analogvoltchangelvalue)
  return analogvoltchangelvalue_.Mutable(index);
}
::OutPutCommon::chanelpara* acanalogpara::add_analogvoltchangelvalue() {
  // @@protoc_insertion_point(field_add:OutPutCommon.acanalogpara.analogvoltchangelvalue)
  return analogvoltchangelvalue_.Add();
}
::google::protobuf::RepeatedPtrField< ::OutPutCommon::chanelpara >*
acanalogpara::mutable_analogvoltchangelvalue() {
  // @@protoc_insertion_point(field_mutable_list:OutPutCommon.acanalogpara.analogvoltchangelvalue)
  return &analogvoltchangelvalue_;
}
const ::google::protobuf::RepeatedPtrField< ::OutPutCommon::chanelpara >&
acanalogpara::analogvoltchangelvalue() const {
  // @@protoc_insertion_point(field_list:OutPutCommon.acanalogpara.analogvoltchangelvalue)
  return analogvoltchangelvalue_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace OutPutCommon

// @@protoc_insertion_point(global_scope)
