// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stateTest.proto

#ifndef PROTOBUF_stateTest_2eproto__INCLUDED
#define PROTOBUF_stateTest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "OutPutCommon.pb.h"
#include "hqyGoosePublish.pb.h"
// @@protoc_insertion_point(includes)
namespace OutPutCommon {
class GradientPara;
class GradientParaDefaultTypeInternal;
extern GradientParaDefaultTypeInternal _GradientPara_default_instance_;
class acanalogpara;
class acanalogparaDefaultTypeInternal;
extern acanalogparaDefaultTypeInternal _acanalogpara_default_instance_;
class chanelpara;
class chanelparaDefaultTypeInternal;
extern chanelparaDefaultTypeInternal _chanelpara_default_instance_;
}  // namespace OutPutCommon
namespace StatePara {
class CommonPara;
class CommonParaDefaultTypeInternal;
extern CommonParaDefaultTypeInternal _CommonPara_default_instance_;
class GradientPara;
class GradientParaDefaultTypeInternal;
extern GradientParaDefaultTypeInternal _GradientPara_default_instance_;
class result;
class resultDefaultTypeInternal;
extern resultDefaultTypeInternal _result_default_instance_;
class resultItem;
class resultItemDefaultTypeInternal;
extern resultItemDefaultTypeInternal _resultItem_default_instance_;
class state;
class stateDefaultTypeInternal;
extern stateDefaultTypeInternal _state_default_instance_;
class states;
class statesDefaultTypeInternal;
extern statesDefaultTypeInternal _states_default_instance_;
}  // namespace StatePara
namespace hqyGoose_Pub_Setting {
class Control_Block;
class Control_BlockDefaultTypeInternal;
extern Control_BlockDefaultTypeInternal _Control_Block_default_instance_;
class Goose_Publish;
class Goose_PublishDefaultTypeInternal;
extern Goose_PublishDefaultTypeInternal _Goose_Publish_default_instance_;
}  // namespace hqyGoose_Pub_Setting

namespace StatePara {

namespace protobuf_stateTest_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_stateTest_2eproto

// ===================================================================

class CommonPara : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:StatePara.CommonPara) */ {
 public:
  CommonPara();
  virtual ~CommonPara();

  CommonPara(const CommonPara& from);

  inline CommonPara& operator=(const CommonPara& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CommonPara& default_instance();

  static inline const CommonPara* internal_default_instance() {
    return reinterpret_cast<const CommonPara*>(
               &_CommonPara_default_instance_);
  }

  void Swap(CommonPara* other);

  // implements Message ----------------------------------------------

  inline CommonPara* New() const PROTOBUF_FINAL { return New(NULL); }

  CommonPara* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CommonPara& from);
  void MergeFrom(const CommonPara& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CommonPara* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 nJudgeCondition = 1;
  void clear_njudgecondition();
  static const int kNJudgeConditionFieldNumber = 1;
  ::google::protobuf::uint32 njudgecondition() const;
  void set_njudgecondition(::google::protobuf::uint32 value);

  // uint32 nDCOFFSET = 2;
  void clear_ndcoffset();
  static const int kNDCOFFSETFieldNumber = 2;
  ::google::protobuf::uint32 ndcoffset() const;
  void set_ndcoffset(::google::protobuf::uint32 value);

  // float fTou = 3;
  void clear_ftou();
  static const int kFTouFieldNumber = 3;
  float ftou() const;
  void set_ftou(float value);

  // uint32 nLoopNum = 4;
  void clear_nloopnum();
  static const int kNLoopNumFieldNumber = 4;
  ::google::protobuf::uint32 nloopnum() const;
  void set_nloopnum(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:StatePara.CommonPara)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 njudgecondition_;
  ::google::protobuf::uint32 ndcoffset_;
  float ftou_;
  ::google::protobuf::uint32 nloopnum_;
  mutable int _cached_size_;
  friend struct  protobuf_stateTest_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class GradientPara : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:StatePara.GradientPara) */ {
 public:
  GradientPara();
  virtual ~GradientPara();

  GradientPara(const GradientPara& from);

  inline GradientPara& operator=(const GradientPara& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GradientPara& default_instance();

  static inline const GradientPara* internal_default_instance() {
    return reinterpret_cast<const GradientPara*>(
               &_GradientPara_default_instance_);
  }

  void Swap(GradientPara* other);

  // implements Message ----------------------------------------------

  inline GradientPara* New() const PROTOBUF_FINAL { return New(NULL); }

  GradientPara* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GradientPara& from);
  void MergeFrom(const GradientPara& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GradientPara* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool bdfdt = 1;
  void clear_bdfdt();
  static const int kBdfdtFieldNumber = 1;
  bool bdfdt() const;
  void set_bdfdt(bool value);

  // bool bdvdt = 2;
  void clear_bdvdt();
  static const int kBdvdtFieldNumber = 2;
  bool bdvdt() const;
  void set_bdvdt(bool value);

  // bool bComGradient = 3;
  void clear_bcomgradient();
  static const int kBComGradientFieldNumber = 3;
  bool bcomgradient() const;
  void set_bcomgradient(bool value);

  // .OutPutCommon.para_type iVar = 4;
  void clear_ivar();
  static const int kIVarFieldNumber = 4;
  ::OutPutCommon::para_type ivar() const;
  void set_ivar(::OutPutCommon::para_type value);

  // float fdfdt = 5;
  void clear_fdfdt();
  static const int kFdfdtFieldNumber = 5;
  float fdfdt() const;
  void set_fdfdt(float value);

  // float fdvdt = 6;
  void clear_fdvdt();
  static const int kFdvdtFieldNumber = 6;
  float fdvdt() const;
  void set_fdvdt(float value);

  // float fStartV = 7;
  void clear_fstartv();
  static const int kFStartVFieldNumber = 7;
  float fstartv() const;
  void set_fstartv(float value);

  // float fStartHz = 8;
  void clear_fstarthz();
  static const int kFStartHzFieldNumber = 8;
  float fstarthz() const;
  void set_fstarthz(float value);

  // float fEndHz = 9;
  void clear_fendhz();
  static const int kFEndHzFieldNumber = 9;
  float fendhz() const;
  void set_fendhz(float value);

  // float fEndV = 10;
  void clear_fendv();
  static const int kFEndVFieldNumber = 10;
  float fendv() const;
  void set_fendv(float value);

  // float fTrigerV = 11;
  void clear_ftrigerv();
  static const int kFTrigerVFieldNumber = 11;
  float ftrigerv() const;
  void set_ftrigerv(float value);

  // float fStep = 12;
  void clear_fstep();
  static const int kFStepFieldNumber = 12;
  float fstep() const;
  void set_fstep(float value);

  // float fStepTime = 13;
  void clear_fsteptime();
  static const int kFStepTimeFieldNumber = 13;
  float fsteptime() const;
  void set_fsteptime(float value);

  // float fEnd = 14;
  void clear_fend();
  static const int kFEndFieldNumber = 14;
  float fend() const;
  void set_fend(float value);

  // float fStart = 15;
  void clear_fstart();
  static const int kFStartFieldNumber = 15;
  float fstart() const;
  void set_fstart(float value);

  // @@protoc_insertion_point(class_scope:StatePara.GradientPara)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool bdfdt_;
  bool bdvdt_;
  bool bcomgradient_;
  int ivar_;
  float fdfdt_;
  float fdvdt_;
  float fstartv_;
  float fstarthz_;
  float fendhz_;
  float fendv_;
  float ftrigerv_;
  float fstep_;
  float fsteptime_;
  float fend_;
  float fstart_;
  mutable int _cached_size_;
  friend struct  protobuf_stateTest_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class state : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:StatePara.state) */ {
 public:
  state();
  virtual ~state();

  state(const state& from);

  inline state& operator=(const state& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const state& default_instance();

  static inline const state* internal_default_instance() {
    return reinterpret_cast<const state*>(
               &_state_default_instance_);
  }

  void Swap(state* other);

  // implements Message ----------------------------------------------

  inline state* New() const PROTOBUF_FINAL { return New(NULL); }

  state* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const state& from);
  void MergeFrom(const state& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(state* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .OutPutCommon.acanalogpara oacAnalogpara = 13;
  bool has_oacanalogpara() const;
  void clear_oacanalogpara();
  static const int kOacAnalogparaFieldNumber = 13;
  const ::OutPutCommon::acanalogpara& oacanalogpara() const;
  ::OutPutCommon::acanalogpara* mutable_oacanalogpara();
  ::OutPutCommon::acanalogpara* release_oacanalogpara();
  void set_allocated_oacanalogpara(::OutPutCommon::acanalogpara* oacanalogpara);

  // .OutPutCommon.acanalogpara oacDigitalpara = 14;
  bool has_oacdigitalpara() const;
  void clear_oacdigitalpara();
  static const int kOacDigitalparaFieldNumber = 14;
  const ::OutPutCommon::acanalogpara& oacdigitalpara() const;
  ::OutPutCommon::acanalogpara* mutable_oacdigitalpara();
  ::OutPutCommon::acanalogpara* release_oacdigitalpara();
  void set_allocated_oacdigitalpara(::OutPutCommon::acanalogpara* oacdigitalpara);

  // .StatePara.GradientPara oanaGradientpara = 15;
  bool has_oanagradientpara() const;
  void clear_oanagradientpara();
  static const int kOanaGradientparaFieldNumber = 15;
  const ::StatePara::GradientPara& oanagradientpara() const;
  ::StatePara::GradientPara* mutable_oanagradientpara();
  ::StatePara::GradientPara* release_oanagradientpara();
  void set_allocated_oanagradientpara(::StatePara::GradientPara* oanagradientpara);

  // .StatePara.GradientPara odigGradientpara = 16;
  bool has_odiggradientpara() const;
  void clear_odiggradientpara();
  static const int kOdigGradientparaFieldNumber = 16;
  const ::StatePara::GradientPara& odiggradientpara() const;
  ::StatePara::GradientPara* mutable_odiggradientpara();
  ::StatePara::GradientPara* release_odiggradientpara();
  void set_allocated_odiggradientpara(::StatePara::GradientPara* odiggradientpara);

  // .hqyGoose_Pub_Setting.Goose_Publish GooseChanged = 18;
  bool has_goosechanged() const;
  void clear_goosechanged();
  static const int kGooseChangedFieldNumber = 18;
  const ::hqyGoose_Pub_Setting::Goose_Publish& goosechanged() const;
  ::hqyGoose_Pub_Setting::Goose_Publish* mutable_goosechanged();
  ::hqyGoose_Pub_Setting::Goose_Publish* release_goosechanged();
  void set_allocated_goosechanged(::hqyGoose_Pub_Setting::Goose_Publish* goosechanged);

  // uint32 nIndex = 1;
  void clear_nindex();
  static const int kNIndexFieldNumber = 1;
  ::google::protobuf::uint32 nindex() const;
  void set_nindex(::google::protobuf::uint32 value);

  // uint32 nTrigerType = 3;
  void clear_ntrigertype();
  static const int kNTrigerTypeFieldNumber = 3;
  ::google::protobuf::uint32 ntrigertype() const;
  void set_ntrigertype(::google::protobuf::uint32 value);

  // float fOutPutTime = 4;
  void clear_foutputtime();
  static const int kFOutPutTimeFieldNumber = 4;
  float foutputtime() const;
  void set_foutputtime(float value);

  // uint32 sGpstime = 5;
  void clear_sgpstime();
  static const int kSGpstimeFieldNumber = 5;
  ::google::protobuf::uint32 sgpstime() const;
  void set_sgpstime(::google::protobuf::uint32 value);

  // uint32 nsGpsTime = 6;
  void clear_nsgpstime();
  static const int kNsGpsTimeFieldNumber = 6;
  ::google::protobuf::uint32 nsgpstime() const;
  void set_nsgpstime(::google::protobuf::uint32 value);

  // bool bDc = 2;
  void clear_bdc();
  static const int kBDcFieldNumber = 2;
  bool bdc() const;
  void set_bdc(bool value);

  // bool bBoInvert = 11;
  void clear_bboinvert();
  static const int kBBoInvertFieldNumber = 11;
  bool bboinvert() const;
  void set_bboinvert(bool value);

  // float fTrigerHoldTime = 7;
  void clear_ftrigerholdtime();
  static const int kFTrigerHoldTimeFieldNumber = 7;
  float ftrigerholdtime() const;
  void set_ftrigerholdtime(float value);

  // uint32 nBiValide = 8;
  void clear_nbivalide();
  static const int kNBiValideFieldNumber = 8;
  ::google::protobuf::uint32 nbivalide() const;
  void set_nbivalide(::google::protobuf::uint32 value);

  // uint32 nBiLogic = 9;
  void clear_nbilogic();
  static const int kNBiLogicFieldNumber = 9;
  ::google::protobuf::uint32 nbilogic() const;
  void set_nbilogic(::google::protobuf::uint32 value);

  // uint32 nBoValide = 10;
  void clear_nbovalide();
  static const int kNBoValideFieldNumber = 10;
  ::google::protobuf::uint32 nbovalide() const;
  void set_nbovalide(::google::protobuf::uint32 value);

  // float fBoHoldTime = 12;
  void clear_fboholdtime();
  static const int kFBoHoldTimeFieldNumber = 12;
  float fboholdtime() const;
  void set_fboholdtime(float value);

  // uint32 nBiDigitalValide = 17;
  void clear_nbidigitalvalide();
  static const int kNBiDigitalValideFieldNumber = 17;
  ::google::protobuf::uint32 nbidigitalvalide() const;
  void set_nbidigitalvalide(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:StatePara.state)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::OutPutCommon::acanalogpara* oacanalogpara_;
  ::OutPutCommon::acanalogpara* oacdigitalpara_;
  ::StatePara::GradientPara* oanagradientpara_;
  ::StatePara::GradientPara* odiggradientpara_;
  ::hqyGoose_Pub_Setting::Goose_Publish* goosechanged_;
  ::google::protobuf::uint32 nindex_;
  ::google::protobuf::uint32 ntrigertype_;
  float foutputtime_;
  ::google::protobuf::uint32 sgpstime_;
  ::google::protobuf::uint32 nsgpstime_;
  bool bdc_;
  bool bboinvert_;
  float ftrigerholdtime_;
  ::google::protobuf::uint32 nbivalide_;
  ::google::protobuf::uint32 nbilogic_;
  ::google::protobuf::uint32 nbovalide_;
  float fboholdtime_;
  ::google::protobuf::uint32 nbidigitalvalide_;
  mutable int _cached_size_;
  friend struct  protobuf_stateTest_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class states : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:StatePara.states) */ {
 public:
  states();
  virtual ~states();

  states(const states& from);

  inline states& operator=(const states& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const states& default_instance();

  static inline const states* internal_default_instance() {
    return reinterpret_cast<const states*>(
               &_states_default_instance_);
  }

  void Swap(states* other);

  // implements Message ----------------------------------------------

  inline states* New() const PROTOBUF_FINAL { return New(NULL); }

  states* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const states& from);
  void MergeFrom(const states& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(states* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .StatePara.state ostates = 2;
  int ostates_size() const;
  void clear_ostates();
  static const int kOstatesFieldNumber = 2;
  const ::StatePara::state& ostates(int index) const;
  ::StatePara::state* mutable_ostates(int index);
  ::StatePara::state* add_ostates();
  ::google::protobuf::RepeatedPtrField< ::StatePara::state >*
      mutable_ostates();
  const ::google::protobuf::RepeatedPtrField< ::StatePara::state >&
      ostates() const;

  // .StatePara.CommonPara ocommon = 1;
  bool has_ocommon() const;
  void clear_ocommon();
  static const int kOcommonFieldNumber = 1;
  const ::StatePara::CommonPara& ocommon() const;
  ::StatePara::CommonPara* mutable_ocommon();
  ::StatePara::CommonPara* release_ocommon();
  void set_allocated_ocommon(::StatePara::CommonPara* ocommon);

  // @@protoc_insertion_point(class_scope:StatePara.states)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::StatePara::state > ostates_;
  ::StatePara::CommonPara* ocommon_;
  mutable int _cached_size_;
  friend struct  protobuf_stateTest_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class resultItem : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:StatePara.resultItem) */ {
 public:
  resultItem();
  virtual ~resultItem();

  resultItem(const resultItem& from);

  inline resultItem& operator=(const resultItem& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const resultItem& default_instance();

  static inline const resultItem* internal_default_instance() {
    return reinterpret_cast<const resultItem*>(
               &_resultItem_default_instance_);
  }

  void Swap(resultItem* other);

  // implements Message ----------------------------------------------

  inline resultItem* New() const PROTOBUF_FINAL { return New(NULL); }

  resultItem* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const resultItem& from);
  void MergeFrom(const resultItem& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(resultItem* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint32 nType = 1;
  void clear_ntype();
  static const int kNTypeFieldNumber = 1;
  ::google::protobuf::uint32 ntype() const;
  void set_ntype(::google::protobuf::uint32 value);

  // uint32 nSource = 2;
  void clear_nsource();
  static const int kNSourceFieldNumber = 2;
  ::google::protobuf::uint32 nsource() const;
  void set_nsource(::google::protobuf::uint32 value);

  // uint32 nSec = 3;
  void clear_nsec();
  static const int kNSecFieldNumber = 3;
  ::google::protobuf::uint32 nsec() const;
  void set_nsec(::google::protobuf::uint32 value);

  // uint32 nNanoSec = 4;
  void clear_nnanosec();
  static const int kNNanoSecFieldNumber = 4;
  ::google::protobuf::uint32 nnanosec() const;
  void set_nnanosec(::google::protobuf::uint32 value);

  // uint32 nInput = 5;
  void clear_ninput();
  static const int kNInputFieldNumber = 5;
  ::google::protobuf::uint32 ninput() const;
  void set_ninput(::google::protobuf::uint32 value);

  // uint32 nGooseValue = 6;
  void clear_ngoosevalue();
  static const int kNGooseValueFieldNumber = 6;
  ::google::protobuf::uint32 ngoosevalue() const;
  void set_ngoosevalue(::google::protobuf::uint32 value);

  // uint32 currentIndex = 7;
  void clear_currentindex();
  static const int kCurrentIndexFieldNumber = 7;
  ::google::protobuf::uint32 currentindex() const;
  void set_currentindex(::google::protobuf::uint32 value);

  // uint32 nObjective = 8;
  void clear_nobjective();
  static const int kNObjectiveFieldNumber = 8;
  ::google::protobuf::uint32 nobjective() const;
  void set_nobjective(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:StatePara.resultItem)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 ntype_;
  ::google::protobuf::uint32 nsource_;
  ::google::protobuf::uint32 nsec_;
  ::google::protobuf::uint32 nnanosec_;
  ::google::protobuf::uint32 ninput_;
  ::google::protobuf::uint32 ngoosevalue_;
  ::google::protobuf::uint32 currentindex_;
  ::google::protobuf::uint32 nobjective_;
  mutable int _cached_size_;
  friend struct  protobuf_stateTest_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class result : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:StatePara.result) */ {
 public:
  result();
  virtual ~result();

  result(const result& from);

  inline result& operator=(const result& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const result& default_instance();

  static inline const result* internal_default_instance() {
    return reinterpret_cast<const result*>(
               &_result_default_instance_);
  }

  void Swap(result* other);

  // implements Message ----------------------------------------------

  inline result* New() const PROTOBUF_FINAL { return New(NULL); }

  result* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const result& from);
  void MergeFrom(const result& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(result* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .StatePara.resultItem oreslult = 1;
  int oreslult_size() const;
  void clear_oreslult();
  static const int kOreslultFieldNumber = 1;
  const ::StatePara::resultItem& oreslult(int index) const;
  ::StatePara::resultItem* mutable_oreslult(int index);
  ::StatePara::resultItem* add_oreslult();
  ::google::protobuf::RepeatedPtrField< ::StatePara::resultItem >*
      mutable_oreslult();
  const ::google::protobuf::RepeatedPtrField< ::StatePara::resultItem >&
      oreslult() const;

  // @@protoc_insertion_point(class_scope:StatePara.result)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::StatePara::resultItem > oreslult_;
  mutable int _cached_size_;
  friend struct  protobuf_stateTest_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// CommonPara

// uint32 nJudgeCondition = 1;
inline void CommonPara::clear_njudgecondition() {
  njudgecondition_ = 0u;
}
inline ::google::protobuf::uint32 CommonPara::njudgecondition() const {
  // @@protoc_insertion_point(field_get:StatePara.CommonPara.nJudgeCondition)
  return njudgecondition_;
}
inline void CommonPara::set_njudgecondition(::google::protobuf::uint32 value) {
  
  njudgecondition_ = value;
  // @@protoc_insertion_point(field_set:StatePara.CommonPara.nJudgeCondition)
}

// uint32 nDCOFFSET = 2;
inline void CommonPara::clear_ndcoffset() {
  ndcoffset_ = 0u;
}
inline ::google::protobuf::uint32 CommonPara::ndcoffset() const {
  // @@protoc_insertion_point(field_get:StatePara.CommonPara.nDCOFFSET)
  return ndcoffset_;
}
inline void CommonPara::set_ndcoffset(::google::protobuf::uint32 value) {
  
  ndcoffset_ = value;
  // @@protoc_insertion_point(field_set:StatePara.CommonPara.nDCOFFSET)
}

// float fTou = 3;
inline void CommonPara::clear_ftou() {
  ftou_ = 0;
}
inline float CommonPara::ftou() const {
  // @@protoc_insertion_point(field_get:StatePara.CommonPara.fTou)
  return ftou_;
}
inline void CommonPara::set_ftou(float value) {
  
  ftou_ = value;
  // @@protoc_insertion_point(field_set:StatePara.CommonPara.fTou)
}

// uint32 nLoopNum = 4;
inline void CommonPara::clear_nloopnum() {
  nloopnum_ = 0u;
}
inline ::google::protobuf::uint32 CommonPara::nloopnum() const {
  // @@protoc_insertion_point(field_get:StatePara.CommonPara.nLoopNum)
  return nloopnum_;
}
inline void CommonPara::set_nloopnum(::google::protobuf::uint32 value) {
  
  nloopnum_ = value;
  // @@protoc_insertion_point(field_set:StatePara.CommonPara.nLoopNum)
}

// -------------------------------------------------------------------

// GradientPara

// bool bdfdt = 1;
inline void GradientPara::clear_bdfdt() {
  bdfdt_ = false;
}
inline bool GradientPara::bdfdt() const {
  // @@protoc_insertion_point(field_get:StatePara.GradientPara.bdfdt)
  return bdfdt_;
}
inline void GradientPara::set_bdfdt(bool value) {
  
  bdfdt_ = value;
  // @@protoc_insertion_point(field_set:StatePara.GradientPara.bdfdt)
}

// bool bdvdt = 2;
inline void GradientPara::clear_bdvdt() {
  bdvdt_ = false;
}
inline bool GradientPara::bdvdt() const {
  // @@protoc_insertion_point(field_get:StatePara.GradientPara.bdvdt)
  return bdvdt_;
}
inline void GradientPara::set_bdvdt(bool value) {
  
  bdvdt_ = value;
  // @@protoc_insertion_point(field_set:StatePara.GradientPara.bdvdt)
}

// bool bComGradient = 3;
inline void GradientPara::clear_bcomgradient() {
  bcomgradient_ = false;
}
inline bool GradientPara::bcomgradient() const {
  // @@protoc_insertion_point(field_get:StatePara.GradientPara.bComGradient)
  return bcomgradient_;
}
inline void GradientPara::set_bcomgradient(bool value) {
  
  bcomgradient_ = value;
  // @@protoc_insertion_point(field_set:StatePara.GradientPara.bComGradient)
}

// .OutPutCommon.para_type iVar = 4;
inline void GradientPara::clear_ivar() {
  ivar_ = 0;
}
inline ::OutPutCommon::para_type GradientPara::ivar() const {
  // @@protoc_insertion_point(field_get:StatePara.GradientPara.iVar)
  return static_cast< ::OutPutCommon::para_type >(ivar_);
}
inline void GradientPara::set_ivar(::OutPutCommon::para_type value) {
  
  ivar_ = value;
  // @@protoc_insertion_point(field_set:StatePara.GradientPara.iVar)
}

// float fdfdt = 5;
inline void GradientPara::clear_fdfdt() {
  fdfdt_ = 0;
}
inline float GradientPara::fdfdt() const {
  // @@protoc_insertion_point(field_get:StatePara.GradientPara.fdfdt)
  return fdfdt_;
}
inline void GradientPara::set_fdfdt(float value) {
  
  fdfdt_ = value;
  // @@protoc_insertion_point(field_set:StatePara.GradientPara.fdfdt)
}

// float fdvdt = 6;
inline void GradientPara::clear_fdvdt() {
  fdvdt_ = 0;
}
inline float GradientPara::fdvdt() const {
  // @@protoc_insertion_point(field_get:StatePara.GradientPara.fdvdt)
  return fdvdt_;
}
inline void GradientPara::set_fdvdt(float value) {
  
  fdvdt_ = value;
  // @@protoc_insertion_point(field_set:StatePara.GradientPara.fdvdt)
}

// float fStartV = 7;
inline void GradientPara::clear_fstartv() {
  fstartv_ = 0;
}
inline float GradientPara::fstartv() const {
  // @@protoc_insertion_point(field_get:StatePara.GradientPara.fStartV)
  return fstartv_;
}
inline void GradientPara::set_fstartv(float value) {
  
  fstartv_ = value;
  // @@protoc_insertion_point(field_set:StatePara.GradientPara.fStartV)
}

// float fStartHz = 8;
inline void GradientPara::clear_fstarthz() {
  fstarthz_ = 0;
}
inline float GradientPara::fstarthz() const {
  // @@protoc_insertion_point(field_get:StatePara.GradientPara.fStartHz)
  return fstarthz_;
}
inline void GradientPara::set_fstarthz(float value) {
  
  fstarthz_ = value;
  // @@protoc_insertion_point(field_set:StatePara.GradientPara.fStartHz)
}

// float fEndHz = 9;
inline void GradientPara::clear_fendhz() {
  fendhz_ = 0;
}
inline float GradientPara::fendhz() const {
  // @@protoc_insertion_point(field_get:StatePara.GradientPara.fEndHz)
  return fendhz_;
}
inline void GradientPara::set_fendhz(float value) {
  
  fendhz_ = value;
  // @@protoc_insertion_point(field_set:StatePara.GradientPara.fEndHz)
}

// float fEndV = 10;
inline void GradientPara::clear_fendv() {
  fendv_ = 0;
}
inline float GradientPara::fendv() const {
  // @@protoc_insertion_point(field_get:StatePara.GradientPara.fEndV)
  return fendv_;
}
inline void GradientPara::set_fendv(float value) {
  
  fendv_ = value;
  // @@protoc_insertion_point(field_set:StatePara.GradientPara.fEndV)
}

// float fTrigerV = 11;
inline void GradientPara::clear_ftrigerv() {
  ftrigerv_ = 0;
}
inline float GradientPara::ftrigerv() const {
  // @@protoc_insertion_point(field_get:StatePara.GradientPara.fTrigerV)
  return ftrigerv_;
}
inline void GradientPara::set_ftrigerv(float value) {
  
  ftrigerv_ = value;
  // @@protoc_insertion_point(field_set:StatePara.GradientPara.fTrigerV)
}

// float fStep = 12;
inline void GradientPara::clear_fstep() {
  fstep_ = 0;
}
inline float GradientPara::fstep() const {
  // @@protoc_insertion_point(field_get:StatePara.GradientPara.fStep)
  return fstep_;
}
inline void GradientPara::set_fstep(float value) {
  
  fstep_ = value;
  // @@protoc_insertion_point(field_set:StatePara.GradientPara.fStep)
}

// float fStepTime = 13;
inline void GradientPara::clear_fsteptime() {
  fsteptime_ = 0;
}
inline float GradientPara::fsteptime() const {
  // @@protoc_insertion_point(field_get:StatePara.GradientPara.fStepTime)
  return fsteptime_;
}
inline void GradientPara::set_fsteptime(float value) {
  
  fsteptime_ = value;
  // @@protoc_insertion_point(field_set:StatePara.GradientPara.fStepTime)
}

// float fEnd = 14;
inline void GradientPara::clear_fend() {
  fend_ = 0;
}
inline float GradientPara::fend() const {
  // @@protoc_insertion_point(field_get:StatePara.GradientPara.fEnd)
  return fend_;
}
inline void GradientPara::set_fend(float value) {
  
  fend_ = value;
  // @@protoc_insertion_point(field_set:StatePara.GradientPara.fEnd)
}

// float fStart = 15;
inline void GradientPara::clear_fstart() {
  fstart_ = 0;
}
inline float GradientPara::fstart() const {
  // @@protoc_insertion_point(field_get:StatePara.GradientPara.fStart)
  return fstart_;
}
inline void GradientPara::set_fstart(float value) {
  
  fstart_ = value;
  // @@protoc_insertion_point(field_set:StatePara.GradientPara.fStart)
}

// -------------------------------------------------------------------

// state

// uint32 nIndex = 1;
inline void state::clear_nindex() {
  nindex_ = 0u;
}
inline ::google::protobuf::uint32 state::nindex() const {
  // @@protoc_insertion_point(field_get:StatePara.state.nIndex)
  return nindex_;
}
inline void state::set_nindex(::google::protobuf::uint32 value) {
  
  nindex_ = value;
  // @@protoc_insertion_point(field_set:StatePara.state.nIndex)
}

// bool bDc = 2;
inline void state::clear_bdc() {
  bdc_ = false;
}
inline bool state::bdc() const {
  // @@protoc_insertion_point(field_get:StatePara.state.bDc)
  return bdc_;
}
inline void state::set_bdc(bool value) {
  
  bdc_ = value;
  // @@protoc_insertion_point(field_set:StatePara.state.bDc)
}

// uint32 nTrigerType = 3;
inline void state::clear_ntrigertype() {
  ntrigertype_ = 0u;
}
inline ::google::protobuf::uint32 state::ntrigertype() const {
  // @@protoc_insertion_point(field_get:StatePara.state.nTrigerType)
  return ntrigertype_;
}
inline void state::set_ntrigertype(::google::protobuf::uint32 value) {
  
  ntrigertype_ = value;
  // @@protoc_insertion_point(field_set:StatePara.state.nTrigerType)
}

// float fOutPutTime = 4;
inline void state::clear_foutputtime() {
  foutputtime_ = 0;
}
inline float state::foutputtime() const {
  // @@protoc_insertion_point(field_get:StatePara.state.fOutPutTime)
  return foutputtime_;
}
inline void state::set_foutputtime(float value) {
  
  foutputtime_ = value;
  // @@protoc_insertion_point(field_set:StatePara.state.fOutPutTime)
}

// uint32 sGpstime = 5;
inline void state::clear_sgpstime() {
  sgpstime_ = 0u;
}
inline ::google::protobuf::uint32 state::sgpstime() const {
  // @@protoc_insertion_point(field_get:StatePara.state.sGpstime)
  return sgpstime_;
}
inline void state::set_sgpstime(::google::protobuf::uint32 value) {
  
  sgpstime_ = value;
  // @@protoc_insertion_point(field_set:StatePara.state.sGpstime)
}

// uint32 nsGpsTime = 6;
inline void state::clear_nsgpstime() {
  nsgpstime_ = 0u;
}
inline ::google::protobuf::uint32 state::nsgpstime() const {
  // @@protoc_insertion_point(field_get:StatePara.state.nsGpsTime)
  return nsgpstime_;
}
inline void state::set_nsgpstime(::google::protobuf::uint32 value) {
  
  nsgpstime_ = value;
  // @@protoc_insertion_point(field_set:StatePara.state.nsGpsTime)
}

// float fTrigerHoldTime = 7;
inline void state::clear_ftrigerholdtime() {
  ftrigerholdtime_ = 0;
}
inline float state::ftrigerholdtime() const {
  // @@protoc_insertion_point(field_get:StatePara.state.fTrigerHoldTime)
  return ftrigerholdtime_;
}
inline void state::set_ftrigerholdtime(float value) {
  
  ftrigerholdtime_ = value;
  // @@protoc_insertion_point(field_set:StatePara.state.fTrigerHoldTime)
}

// uint32 nBiValide = 8;
inline void state::clear_nbivalide() {
  nbivalide_ = 0u;
}
inline ::google::protobuf::uint32 state::nbivalide() const {
  // @@protoc_insertion_point(field_get:StatePara.state.nBiValide)
  return nbivalide_;
}
inline void state::set_nbivalide(::google::protobuf::uint32 value) {
  
  nbivalide_ = value;
  // @@protoc_insertion_point(field_set:StatePara.state.nBiValide)
}

// uint32 nBiLogic = 9;
inline void state::clear_nbilogic() {
  nbilogic_ = 0u;
}
inline ::google::protobuf::uint32 state::nbilogic() const {
  // @@protoc_insertion_point(field_get:StatePara.state.nBiLogic)
  return nbilogic_;
}
inline void state::set_nbilogic(::google::protobuf::uint32 value) {
  
  nbilogic_ = value;
  // @@protoc_insertion_point(field_set:StatePara.state.nBiLogic)
}

// uint32 nBoValide = 10;
inline void state::clear_nbovalide() {
  nbovalide_ = 0u;
}
inline ::google::protobuf::uint32 state::nbovalide() const {
  // @@protoc_insertion_point(field_get:StatePara.state.nBoValide)
  return nbovalide_;
}
inline void state::set_nbovalide(::google::protobuf::uint32 value) {
  
  nbovalide_ = value;
  // @@protoc_insertion_point(field_set:StatePara.state.nBoValide)
}

// bool bBoInvert = 11;
inline void state::clear_bboinvert() {
  bboinvert_ = false;
}
inline bool state::bboinvert() const {
  // @@protoc_insertion_point(field_get:StatePara.state.bBoInvert)
  return bboinvert_;
}
inline void state::set_bboinvert(bool value) {
  
  bboinvert_ = value;
  // @@protoc_insertion_point(field_set:StatePara.state.bBoInvert)
}

// float fBoHoldTime = 12;
inline void state::clear_fboholdtime() {
  fboholdtime_ = 0;
}
inline float state::fboholdtime() const {
  // @@protoc_insertion_point(field_get:StatePara.state.fBoHoldTime)
  return fboholdtime_;
}
inline void state::set_fboholdtime(float value) {
  
  fboholdtime_ = value;
  // @@protoc_insertion_point(field_set:StatePara.state.fBoHoldTime)
}

// .OutPutCommon.acanalogpara oacAnalogpara = 13;
inline bool state::has_oacanalogpara() const {
  return this != internal_default_instance() && oacanalogpara_ != NULL;
}
inline void state::clear_oacanalogpara() {
  if (GetArenaNoVirtual() == NULL && oacanalogpara_ != NULL) delete oacanalogpara_;
  oacanalogpara_ = NULL;
}
inline const ::OutPutCommon::acanalogpara& state::oacanalogpara() const {
  // @@protoc_insertion_point(field_get:StatePara.state.oacAnalogpara)
  return oacanalogpara_ != NULL ? *oacanalogpara_
                         : *::OutPutCommon::acanalogpara::internal_default_instance();
}
inline ::OutPutCommon::acanalogpara* state::mutable_oacanalogpara() {
  
  if (oacanalogpara_ == NULL) {
    oacanalogpara_ = new ::OutPutCommon::acanalogpara;
  }
  // @@protoc_insertion_point(field_mutable:StatePara.state.oacAnalogpara)
  return oacanalogpara_;
}
inline ::OutPutCommon::acanalogpara* state::release_oacanalogpara() {
  // @@protoc_insertion_point(field_release:StatePara.state.oacAnalogpara)
  
  ::OutPutCommon::acanalogpara* temp = oacanalogpara_;
  oacanalogpara_ = NULL;
  return temp;
}
inline void state::set_allocated_oacanalogpara(::OutPutCommon::acanalogpara* oacanalogpara) {
  delete oacanalogpara_;
  oacanalogpara_ = oacanalogpara;
  if (oacanalogpara) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:StatePara.state.oacAnalogpara)
}

// .OutPutCommon.acanalogpara oacDigitalpara = 14;
inline bool state::has_oacdigitalpara() const {
  return this != internal_default_instance() && oacdigitalpara_ != NULL;
}
inline void state::clear_oacdigitalpara() {
  if (GetArenaNoVirtual() == NULL && oacdigitalpara_ != NULL) delete oacdigitalpara_;
  oacdigitalpara_ = NULL;
}
inline const ::OutPutCommon::acanalogpara& state::oacdigitalpara() const {
  // @@protoc_insertion_point(field_get:StatePara.state.oacDigitalpara)
  return oacdigitalpara_ != NULL ? *oacdigitalpara_
                         : *::OutPutCommon::acanalogpara::internal_default_instance();
}
inline ::OutPutCommon::acanalogpara* state::mutable_oacdigitalpara() {
  
  if (oacdigitalpara_ == NULL) {
    oacdigitalpara_ = new ::OutPutCommon::acanalogpara;
  }
  // @@protoc_insertion_point(field_mutable:StatePara.state.oacDigitalpara)
  return oacdigitalpara_;
}
inline ::OutPutCommon::acanalogpara* state::release_oacdigitalpara() {
  // @@protoc_insertion_point(field_release:StatePara.state.oacDigitalpara)
  
  ::OutPutCommon::acanalogpara* temp = oacdigitalpara_;
  oacdigitalpara_ = NULL;
  return temp;
}
inline void state::set_allocated_oacdigitalpara(::OutPutCommon::acanalogpara* oacdigitalpara) {
  delete oacdigitalpara_;
  oacdigitalpara_ = oacdigitalpara;
  if (oacdigitalpara) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:StatePara.state.oacDigitalpara)
}

// .StatePara.GradientPara oanaGradientpara = 15;
inline bool state::has_oanagradientpara() const {
  return this != internal_default_instance() && oanagradientpara_ != NULL;
}
inline void state::clear_oanagradientpara() {
  if (GetArenaNoVirtual() == NULL && oanagradientpara_ != NULL) delete oanagradientpara_;
  oanagradientpara_ = NULL;
}
inline const ::StatePara::GradientPara& state::oanagradientpara() const {
  // @@protoc_insertion_point(field_get:StatePara.state.oanaGradientpara)
  return oanagradientpara_ != NULL ? *oanagradientpara_
                         : *::StatePara::GradientPara::internal_default_instance();
}
inline ::StatePara::GradientPara* state::mutable_oanagradientpara() {
  
  if (oanagradientpara_ == NULL) {
    oanagradientpara_ = new ::StatePara::GradientPara;
  }
  // @@protoc_insertion_point(field_mutable:StatePara.state.oanaGradientpara)
  return oanagradientpara_;
}
inline ::StatePara::GradientPara* state::release_oanagradientpara() {
  // @@protoc_insertion_point(field_release:StatePara.state.oanaGradientpara)
  
  ::StatePara::GradientPara* temp = oanagradientpara_;
  oanagradientpara_ = NULL;
  return temp;
}
inline void state::set_allocated_oanagradientpara(::StatePara::GradientPara* oanagradientpara) {
  delete oanagradientpara_;
  oanagradientpara_ = oanagradientpara;
  if (oanagradientpara) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:StatePara.state.oanaGradientpara)
}

// .StatePara.GradientPara odigGradientpara = 16;
inline bool state::has_odiggradientpara() const {
  return this != internal_default_instance() && odiggradientpara_ != NULL;
}
inline void state::clear_odiggradientpara() {
  if (GetArenaNoVirtual() == NULL && odiggradientpara_ != NULL) delete odiggradientpara_;
  odiggradientpara_ = NULL;
}
inline const ::StatePara::GradientPara& state::odiggradientpara() const {
  // @@protoc_insertion_point(field_get:StatePara.state.odigGradientpara)
  return odiggradientpara_ != NULL ? *odiggradientpara_
                         : *::StatePara::GradientPara::internal_default_instance();
}
inline ::StatePara::GradientPara* state::mutable_odiggradientpara() {
  
  if (odiggradientpara_ == NULL) {
    odiggradientpara_ = new ::StatePara::GradientPara;
  }
  // @@protoc_insertion_point(field_mutable:StatePara.state.odigGradientpara)
  return odiggradientpara_;
}
inline ::StatePara::GradientPara* state::release_odiggradientpara() {
  // @@protoc_insertion_point(field_release:StatePara.state.odigGradientpara)
  
  ::StatePara::GradientPara* temp = odiggradientpara_;
  odiggradientpara_ = NULL;
  return temp;
}
inline void state::set_allocated_odiggradientpara(::StatePara::GradientPara* odiggradientpara) {
  delete odiggradientpara_;
  odiggradientpara_ = odiggradientpara;
  if (odiggradientpara) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:StatePara.state.odigGradientpara)
}

// uint32 nBiDigitalValide = 17;
inline void state::clear_nbidigitalvalide() {
  nbidigitalvalide_ = 0u;
}
inline ::google::protobuf::uint32 state::nbidigitalvalide() const {
  // @@protoc_insertion_point(field_get:StatePara.state.nBiDigitalValide)
  return nbidigitalvalide_;
}
inline void state::set_nbidigitalvalide(::google::protobuf::uint32 value) {
  
  nbidigitalvalide_ = value;
  // @@protoc_insertion_point(field_set:StatePara.state.nBiDigitalValide)
}

// .hqyGoose_Pub_Setting.Goose_Publish GooseChanged = 18;
inline bool state::has_goosechanged() const {
  return this != internal_default_instance() && goosechanged_ != NULL;
}
inline void state::clear_goosechanged() {
  if (GetArenaNoVirtual() == NULL && goosechanged_ != NULL) delete goosechanged_;
  goosechanged_ = NULL;
}
inline const ::hqyGoose_Pub_Setting::Goose_Publish& state::goosechanged() const {
  // @@protoc_insertion_point(field_get:StatePara.state.GooseChanged)
  return goosechanged_ != NULL ? *goosechanged_
                         : *::hqyGoose_Pub_Setting::Goose_Publish::internal_default_instance();
}
inline ::hqyGoose_Pub_Setting::Goose_Publish* state::mutable_goosechanged() {
  
  if (goosechanged_ == NULL) {
    goosechanged_ = new ::hqyGoose_Pub_Setting::Goose_Publish;
  }
  // @@protoc_insertion_point(field_mutable:StatePara.state.GooseChanged)
  return goosechanged_;
}
inline ::hqyGoose_Pub_Setting::Goose_Publish* state::release_goosechanged() {
  // @@protoc_insertion_point(field_release:StatePara.state.GooseChanged)
  
  ::hqyGoose_Pub_Setting::Goose_Publish* temp = goosechanged_;
  goosechanged_ = NULL;
  return temp;
}
inline void state::set_allocated_goosechanged(::hqyGoose_Pub_Setting::Goose_Publish* goosechanged) {
  delete goosechanged_;
  goosechanged_ = goosechanged;
  if (goosechanged) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:StatePara.state.GooseChanged)
}

// -------------------------------------------------------------------

// states

// .StatePara.CommonPara ocommon = 1;
inline bool states::has_ocommon() const {
  return this != internal_default_instance() && ocommon_ != NULL;
}
inline void states::clear_ocommon() {
  if (GetArenaNoVirtual() == NULL && ocommon_ != NULL) delete ocommon_;
  ocommon_ = NULL;
}
inline const ::StatePara::CommonPara& states::ocommon() const {
  // @@protoc_insertion_point(field_get:StatePara.states.ocommon)
  return ocommon_ != NULL ? *ocommon_
                         : *::StatePara::CommonPara::internal_default_instance();
}
inline ::StatePara::CommonPara* states::mutable_ocommon() {
  
  if (ocommon_ == NULL) {
    ocommon_ = new ::StatePara::CommonPara;
  }
  // @@protoc_insertion_point(field_mutable:StatePara.states.ocommon)
  return ocommon_;
}
inline ::StatePara::CommonPara* states::release_ocommon() {
  // @@protoc_insertion_point(field_release:StatePara.states.ocommon)
  
  ::StatePara::CommonPara* temp = ocommon_;
  ocommon_ = NULL;
  return temp;
}
inline void states::set_allocated_ocommon(::StatePara::CommonPara* ocommon) {
  delete ocommon_;
  ocommon_ = ocommon;
  if (ocommon) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:StatePara.states.ocommon)
}

// repeated .StatePara.state ostates = 2;
inline int states::ostates_size() const {
  return ostates_.size();
}
inline void states::clear_ostates() {
  ostates_.Clear();
}
inline const ::StatePara::state& states::ostates(int index) const {
  // @@protoc_insertion_point(field_get:StatePara.states.ostates)
  return ostates_.Get(index);
}
inline ::StatePara::state* states::mutable_ostates(int index) {
  // @@protoc_insertion_point(field_mutable:StatePara.states.ostates)
  return ostates_.Mutable(index);
}
inline ::StatePara::state* states::add_ostates() {
  // @@protoc_insertion_point(field_add:StatePara.states.ostates)
  return ostates_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::StatePara::state >*
states::mutable_ostates() {
  // @@protoc_insertion_point(field_mutable_list:StatePara.states.ostates)
  return &ostates_;
}
inline const ::google::protobuf::RepeatedPtrField< ::StatePara::state >&
states::ostates() const {
  // @@protoc_insertion_point(field_list:StatePara.states.ostates)
  return ostates_;
}

// -------------------------------------------------------------------

// resultItem

// uint32 nType = 1;
inline void resultItem::clear_ntype() {
  ntype_ = 0u;
}
inline ::google::protobuf::uint32 resultItem::ntype() const {
  // @@protoc_insertion_point(field_get:StatePara.resultItem.nType)
  return ntype_;
}
inline void resultItem::set_ntype(::google::protobuf::uint32 value) {
  
  ntype_ = value;
  // @@protoc_insertion_point(field_set:StatePara.resultItem.nType)
}

// uint32 nSource = 2;
inline void resultItem::clear_nsource() {
  nsource_ = 0u;
}
inline ::google::protobuf::uint32 resultItem::nsource() const {
  // @@protoc_insertion_point(field_get:StatePara.resultItem.nSource)
  return nsource_;
}
inline void resultItem::set_nsource(::google::protobuf::uint32 value) {
  
  nsource_ = value;
  // @@protoc_insertion_point(field_set:StatePara.resultItem.nSource)
}

// uint32 nSec = 3;
inline void resultItem::clear_nsec() {
  nsec_ = 0u;
}
inline ::google::protobuf::uint32 resultItem::nsec() const {
  // @@protoc_insertion_point(field_get:StatePara.resultItem.nSec)
  return nsec_;
}
inline void resultItem::set_nsec(::google::protobuf::uint32 value) {
  
  nsec_ = value;
  // @@protoc_insertion_point(field_set:StatePara.resultItem.nSec)
}

// uint32 nNanoSec = 4;
inline void resultItem::clear_nnanosec() {
  nnanosec_ = 0u;
}
inline ::google::protobuf::uint32 resultItem::nnanosec() const {
  // @@protoc_insertion_point(field_get:StatePara.resultItem.nNanoSec)
  return nnanosec_;
}
inline void resultItem::set_nnanosec(::google::protobuf::uint32 value) {
  
  nnanosec_ = value;
  // @@protoc_insertion_point(field_set:StatePara.resultItem.nNanoSec)
}

// uint32 nInput = 5;
inline void resultItem::clear_ninput() {
  ninput_ = 0u;
}
inline ::google::protobuf::uint32 resultItem::ninput() const {
  // @@protoc_insertion_point(field_get:StatePara.resultItem.nInput)
  return ninput_;
}
inline void resultItem::set_ninput(::google::protobuf::uint32 value) {
  
  ninput_ = value;
  // @@protoc_insertion_point(field_set:StatePara.resultItem.nInput)
}

// uint32 nGooseValue = 6;
inline void resultItem::clear_ngoosevalue() {
  ngoosevalue_ = 0u;
}
inline ::google::protobuf::uint32 resultItem::ngoosevalue() const {
  // @@protoc_insertion_point(field_get:StatePara.resultItem.nGooseValue)
  return ngoosevalue_;
}
inline void resultItem::set_ngoosevalue(::google::protobuf::uint32 value) {
  
  ngoosevalue_ = value;
  // @@protoc_insertion_point(field_set:StatePara.resultItem.nGooseValue)
}

// uint32 currentIndex = 7;
inline void resultItem::clear_currentindex() {
  currentindex_ = 0u;
}
inline ::google::protobuf::uint32 resultItem::currentindex() const {
  // @@protoc_insertion_point(field_get:StatePara.resultItem.currentIndex)
  return currentindex_;
}
inline void resultItem::set_currentindex(::google::protobuf::uint32 value) {
  
  currentindex_ = value;
  // @@protoc_insertion_point(field_set:StatePara.resultItem.currentIndex)
}

// uint32 nObjective = 8;
inline void resultItem::clear_nobjective() {
  nobjective_ = 0u;
}
inline ::google::protobuf::uint32 resultItem::nobjective() const {
  // @@protoc_insertion_point(field_get:StatePara.resultItem.nObjective)
  return nobjective_;
}
inline void resultItem::set_nobjective(::google::protobuf::uint32 value) {
  
  nobjective_ = value;
  // @@protoc_insertion_point(field_set:StatePara.resultItem.nObjective)
}

// -------------------------------------------------------------------

// result

// repeated .StatePara.resultItem oreslult = 1;
inline int result::oreslult_size() const {
  return oreslult_.size();
}
inline void result::clear_oreslult() {
  oreslult_.Clear();
}
inline const ::StatePara::resultItem& result::oreslult(int index) const {
  // @@protoc_insertion_point(field_get:StatePara.result.oreslult)
  return oreslult_.Get(index);
}
inline ::StatePara::resultItem* result::mutable_oreslult(int index) {
  // @@protoc_insertion_point(field_mutable:StatePara.result.oreslult)
  return oreslult_.Mutable(index);
}
inline ::StatePara::resultItem* result::add_oreslult() {
  // @@protoc_insertion_point(field_add:StatePara.result.oreslult)
  return oreslult_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::StatePara::resultItem >*
result::mutable_oreslult() {
  // @@protoc_insertion_point(field_mutable_list:StatePara.result.oreslult)
  return &oreslult_;
}
inline const ::google::protobuf::RepeatedPtrField< ::StatePara::resultItem >&
result::oreslult() const {
  // @@protoc_insertion_point(field_list:StatePara.result.oreslult)
  return oreslult_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


}  // namespace StatePara

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_stateTest_2eproto__INCLUDED
